//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_PAR_APLINET_DETALLE
    {
        public int FPA_KEYIDE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public int PAP_KEYPAP { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int PAD_MESINT { get; set; }
        public string PAD_DESPRO { get; set; }
        public System.DateTime PAD_FECALT { get; set; }
        public System.DateTime PAD_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual PA_PAR_APLINET PA_PAR_APLINET { get; set; }
    }
}
