//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_ANIOS_MESES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AM_ANIOS_MESES()
        {
            this.GA_GASTOS_TIENDAS_CONFIG = new HashSet<GA_GASTOS_TIENDAS_CONFIG>();
        }
    
        public int ANM_KEYIDE { get; set; }
        public int ANI_KEYANI { get; set; }
        public short MES_KEYMES { get; set; }
        public System.DateTime ANM_FECINI { get; set; }
        public System.DateTime ANM_FECFIN { get; set; }
        public System.DateTime ANM_FEULAC { get; set; }
        public System.DateTime ANM_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS_CONFIG> GA_GASTOS_TIENDAS_CONFIG { get; set; }
        public virtual CA_ANIOS CA_ANIOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_MESES CA_MESES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
