//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_APARTADOS_HISTORICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AP_APARTADOS_HISTORICO()
        {
            this.AP_APARTADOS_DETALLE_HISTORICO = new HashSet<AP_APARTADOS_DETALLE_HISTORICO>();
        }
    
        public int APA_KEYIDE { get; set; }
        public int APA_KEYAPA { get; set; }
        public Nullable<int> TIE_KEYTIE { get; set; }
        public string APA_NOTIKE { get; set; }
        public Nullable<int> CLI_KEYCLI { get; set; }
        public decimal APA_SALAPA { get; set; }
        public string APA_COMENT { get; set; }
        public System.DateTime APA_FEULAC { get; set; }
        public System.DateTime APA_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE_HISTORICO> AP_APARTADOS_DETALLE_HISTORICO { get; set; }
        public virtual CA_CLIENTES CA_CLIENTES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
