//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_APARTADOS_DETALLE_HISTORICO
    {
        public int APD_KEYAPD { get; set; }
        public int APA_KEYAPA { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int APD_CANTID { get; set; }
        public decimal APD_PRECIO { get; set; }
        public Nullable<int> RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public decimal APD_COSAPA { get; set; }
        public System.DateTime APD_FEULAC { get; set; }
        public System.DateTime APD_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual AP_APARTADOS_HISTORICO AP_APARTADOS_HISTORICO { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
