//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_APARTADOS_DETALLE
    {
        public int APD_KEYIDE { get; set; }
        public int APA_KEYAPA { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int APD_CANTID { get; set; }
        public decimal APD_PRECIO { get; set; }
        public decimal APD_COSAPA { get; set; }
        public System.DateTime APD_FECALT { get; set; }
        public System.DateTime APD_FEULAC { get; set; }
        public int USR_KEYVTA { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual AP_APARTADOS AP_APARTADOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTO_RANGO_TALLAS CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
    }
}
