//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AP_APARTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AP_APARTADOS()
        {
            this.AP_APARTADOS_DETALLE = new HashSet<AP_APARTADOS_DETALLE>();
            this.MA_MOVIMIENTOS_APARTADO = new HashSet<MA_MOVIMIENTOS_APARTADO>();
        }
    
        public int APA_KEYAPA { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int CRE_KEYCRE { get; set; }
        public int CLI_KEYCLI { get; set; }
        public decimal APA_SALAPA { get; set; }
        public string APA_COMENT { get; set; }
        public System.DateTime APA_FECALT { get; set; }
        public System.DateTime APA_FEULAC { get; set; }
        public System.DateTime APA_FECVEN { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
        public Nullable<decimal> APA_PORCEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE> AP_APARTADOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_MOVIMIENTOS_APARTADO> MA_MOVIMIENTOS_APARTADO { get; set; }
        public virtual CA_CAJAS_REGISTRADORAS CA_CAJAS_REGISTRADORAS { get; set; }
        public virtual CA_CLIENTES CA_CLIENTES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIPO_DOCUMENTO CA_TIPO_DOCUMENTO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
