//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_BITACORA_COSTO
    {
        public int BCO_KEYBCO { get; set; }
        public int OCO_KEYOCO { get; set; }
        public string PRD_KEYPRD { get; set; }
        public decimal BIC_COSANT { get; set; }
        public decimal BIC_COSNUE { get; set; }
        public decimal BIC_COSPRO { get; set; }
        public int BIC_CANORD { get; set; }
        public int BIC_CANINV { get; set; }
        public System.DateTime BIC_FECMOV { get; set; }
        public System.DateTime BIC_FEULAC { get; set; }
        public System.DateTime BIC_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual OC_ORDENES_COMPRA OC_ORDENES_COMPRA { get; set; }
    }
}
