//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_BITACORA_CAMBIOS_PRECIOS
    {
        public long BCP_KEYBCP { get; set; }
        public int LIP_KEYLIP { get; set; }
        public decimal LIP_FACANT { get; set; }
        public decimal LIP_FACACT { get; set; }
        public decimal LIP_INCANT { get; set; }
        public decimal LIP_INCACT { get; set; }
        public string PRD_KEYPRD { get; set; }
        public decimal BCP_COSANT { get; set; }
        public decimal BCP_COSACT { get; set; }
        public decimal BCP_PREANT { get; set; }
        public decimal BCP_PREACT { get; set; }
        public System.DateTime BCP_FECREG { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_LISTAS_PRECIOS CA_LISTAS_PRECIOS { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
