//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BC_BIT_CAMBIOS_PRECIOS_TIENDA
    {
        public int BPC_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int USR_KEYVTA { get; set; }
        public int USR_KEYAUT { get; set; }
        public int CRE_KEYCRE { get; set; }
        public int BCP_CANTID { get; set; }
        public decimal BCP_PREANT { get; set; }
        public decimal BCP_PREACT { get; set; }
        public string BCP_CAUSAS { get; set; }
        public System.DateTime BCP_FECALT { get; set; }
        public System.DateTime BCP_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CAJAS_REGISTRADORAS CA_CAJAS_REGISTRADORAS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        public virtual TD_TRANSACCIONES_DETALLE TD_TRANSACCIONES_DETALLE { get; set; }
    }
}
