//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_BITACORA_CAM_VENDEDOR
    {
        public int BIV_KEYIDE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int CRE_KEYCRE { get; set; }
        public int USR_KEYNVO { get; set; }
        public int USR_KEYAUT { get; set; }
        public int USR_KEYANT { get; set; }
        public System.DateTime BIV_FECALT { get; set; }
        public System.DateTime BIV_FEULAC { get; set; }
    
        public virtual CA_CAJAS_REGISTRADORAS CA_CAJAS_REGISTRADORAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS2 { get; set; }
    }
}
