//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BP_BITACORA_PRECIO
    {
        public int BPR_KEYBPR { get; set; }
        public int LIP_KEYLIP { get; set; }
        public string PRD_KEYPRD { get; set; }
        public decimal BPR_COSANT { get; set; }
        public decimal BPR_COSACT { get; set; }
        public decimal BPR_PREANT { get; set; }
        public decimal BPR_PREACT { get; set; }
        public System.DateTime BPR_FECREG { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
