//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_BANCOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_BANCOS()
        {
            this.CA_TIENDAS_BANCOS = new HashSet<CA_TIENDAS_BANCOS>();
            this.DE_DEPOSITOS = new HashSet<DE_DEPOSITOS>();
        }
    
        public int BAN_KEYBAN { get; set; }
        public int CCO_KEYCCO { get; set; }
        public string BAN_CVEBAN { get; set; }
        public string BAN_DESCRI { get; set; }
        public System.DateTime BAN_FEULAC { get; set; }
        public System.DateTime BAN_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS_BANCOS> CA_TIENDAS_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_DEPOSITOS> DE_DEPOSITOS { get; set; }
        public virtual CA_CUENTAS_CONTABLES CA_CUENTAS_CONTABLES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
