//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CAJAS_REGISTRADORAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CAJAS_REGISTRADORAS()
        {
            this.AP_APARTADOS = new HashSet<AP_APARTADOS>();
            this.BC_BIT_CAMBIOS_PRECIOS_TIENDA = new HashSet<BC_BIT_CAMBIOS_PRECIOS_TIENDA>();
            this.BI_BITACORA_CAM_VENDEDOR = new HashSet<BI_BITACORA_CAM_VENDEDOR>();
            this.GA_GASTOS_TIENDAS = new HashSet<GA_GASTOS_TIENDAS>();
            this.TR_TRANSACCIONES = new HashSet<TR_TRANSACCIONES>();
            this.CC_CORTE_CAJA = new HashSet<CC_CORTE_CAJA>();
        }
    
        public int CRE_KEYCRE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string CRE_DESCRI { get; set; }
        public System.DateTime CRE_FEULAC { get; set; }
        public System.DateTime CRE_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS> AP_APARTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BIT_CAMBIOS_PRECIOS_TIENDA> BC_BIT_CAMBIOS_PRECIOS_TIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BI_BITACORA_CAM_VENDEDOR> BI_BITACORA_CAM_VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS> GA_GASTOS_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSACCIONES> TR_TRANSACCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CORTE_CAJA> CC_CORTE_CAJA { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
