//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CLIENTES()
        {
            this.AP_APARTADOS = new HashSet<AP_APARTADOS>();
            this.AP_APARTADOS_HISTORICO = new HashSet<AP_APARTADOS_HISTORICO>();
            this.CA_MEDIOS_CLIENTE = new HashSet<CA_MEDIOS_CLIENTE>();
            this.CF_CLIENTE_FRECUENTE = new HashSet<CF_CLIENTE_FRECUENTE>();
            this.TR_TRANSACCIONES = new HashSet<TR_TRANSACCIONES>();
        }
    
        public int CLI_KEYCLI { get; set; }
        public string CLI_RFCCLI { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_APEPAT { get; set; }
        public string CLI_APEMAT { get; set; }
        public string CLI_DOMICI { get; set; }
        public string CLI_NUMEXT { get; set; }
        public string CLI_NUMINT { get; set; }
        public string CLI_COLONI { get; set; }
        public string CLI_CODPOS { get; set; }
        public int CIU_KEYCIU { get; set; }
        public string CLI_NUMIDE { get; set; }
        public System.DateTime CLI_FECALT { get; set; }
        public System.DateTime CLI_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS> AP_APARTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_HISTORICO> AP_APARTADOS_HISTORICO { get; set; }
        public virtual CA_CIUDADES CA_CIUDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_CLIENTE> CA_MEDIOS_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_CLIENTE_FRECUENTE> CF_CLIENTE_FRECUENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSACCIONES> TR_TRANSACCIONES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
