//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CLIENTES_FACTURACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CLIENTES_FACTURACION()
        {
            this.CA_MEDIOS_CLIENTE_FACTURACION = new HashSet<CA_MEDIOS_CLIENTE_FACTURACION>();
        }
    
        public int CLI_KEYFAC { get; set; }
        public int CLI_TIPPER { get; set; }
        public string CLI_RFCCLI { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_APEPAT { get; set; }
        public string CLI_APEMAT { get; set; }
        public string CLI_DOMICI { get; set; }
        public string CLI_NUMEXT { get; set; }
        public string CLI_NUMINT { get; set; }
        public string CLI_COLONI { get; set; }
        public string CLI_CODPOS { get; set; }
        public int CIU_KEYCIU { get; set; }
        public string CLI_NUMIDE { get; set; }
        public System.DateTime CLI_FECALT { get; set; }
        public System.DateTime CLI_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_CLIENTE_FACTURACION> CA_MEDIOS_CLIENTE_FACTURACION { get; set; }
    }
}
