//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CAUSAS_DEVOLUCIONES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CAUSAS_DEVOLUCIONES()
        {
            this.DP_DEVOLUCIONES_PROVEEDOR_DETALLE = new HashSet<DP_DEVOLUCIONES_PROVEEDOR_DETALLE>();
            this.NC_NOTA_CREDITO = new HashSet<NC_NOTA_CREDITO>();
            this.TR_TRANSFERENCIAS_DETALLE = new HashSet<TR_TRANSFERENCIAS_DETALLE>();
        }
    
        public int CDV_KEYCDV { get; set; }
        public string CDV_DESCRI { get; set; }
        public int CDV_DIAVIG { get; set; }
        public System.DateTime CDV_FEULAC { get; set; }
        public System.DateTime CDV_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
        public bool CDV_DEVPRV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_DEVOLUCIONES_PROVEEDOR_DETALLE> DP_DEVOLUCIONES_PROVEEDOR_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NC_NOTA_CREDITO> NC_NOTA_CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_DETALLE> TR_TRANSFERENCIAS_DETALLE { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
