//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_COMPANIA
    {
        public int COM_KEYCOM { get; set; }
        public string COM_CVECOM { get; set; }
        public string COM_NOMBRE { get; set; }
        public System.DateTime COM_FECALT { get; set; }
        public System.DateTime COM_FEULAC { get; set; }
        public string COM_REFECO { get; set; }
        public string COM_DOMICI { get; set; }
        public string COM_COLONI { get; set; }
        public string COM_CODPOS { get; set; }
        public string COM_NUMEXT { get; set; }
        public string COM_NUMINT { get; set; }
        public int CIU_KEYCIU { get; set; }
        public Nullable<int> COM_NUMAPR { get; set; }
        public Nullable<int> COM_AYOAPR { get; set; }
        public string COM_NUMCER { get; set; }
        public string COM_LEYFAC { get; set; }
        public string COM_TIPCOM { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CIUDADES CA_CIUDADES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
