//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CUENTAS_CONTABLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CUENTAS_CONTABLES()
        {
            this.CA_BANCOS = new HashSet<CA_BANCOS>();
            this.CA_FORMAS_PAGO = new HashSet<CA_FORMAS_PAGO>();
            this.CA_GASTOS = new HashSet<CA_GASTOS>();
        }
    
        public int CCO_KEYCCO { get; set; }
        public string CCO_KEYTIP { get; set; }
        public int CCO_ORDCTA { get; set; }
        public int CCO_CTANIV { get; set; }
        public Nullable<int> MON_KEYMON { get; set; }
        public string CCO_CODCTA { get; set; }
        public string CCO_NOMBRE { get; set; }
        public string CCO_CTAPAD { get; set; }
        public bool CCO_DEDUCI { get; set; }
        public bool CCO_APLBAN { get; set; }
        public bool CCO_DEBHAB { get; set; }
        public bool CCO_APLGAS { get; set; }
        public System.DateTime CCO_FEULAC { get; set; }
        public System.DateTime CCO_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_BANCOS> CA_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_FORMAS_PAGO> CA_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_GASTOS> CA_GASTOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_MONEDAS CA_MONEDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
