//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CIUDADES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CIUDADES()
        {
            this.CA_CLIENTES = new HashSet<CA_CLIENTES>();
            this.CA_COMPANIA = new HashSet<CA_COMPANIA>();
            this.CA_LUGARES_ENTREGAS = new HashSet<CA_LUGARES_ENTREGAS>();
            this.CA_PROVEEDORES = new HashSet<CA_PROVEEDORES>();
            this.CA_TIENDAS = new HashSet<CA_TIENDAS>();
            this.CA_TRANSPORTES = new HashSet<CA_TRANSPORTES>();
        }
    
        public int CIU_KEYCIU { get; set; }
        public Nullable<int> EDO_KEYEDO { get; set; }
        public string CIU_NOMBRE { get; set; }
        public System.DateTime CIU_FEULAC { get; set; }
        public Nullable<System.DateTime> CIU_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CLIENTES> CA_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_COMPANIA> CA_COMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LUGARES_ENTREGAS> CA_LUGARES_ENTREGAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROVEEDORES> CA_PROVEEDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS> CA_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TRANSPORTES> CA_TRANSPORTES { get; set; }
        public virtual CA_ESTADOS CA_ESTADOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
