//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CENTROS_COSTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_CENTROS_COSTOS()
        {
            this.CP_CUENTAS_POR_PAGAR = new HashSet<CP_CUENTAS_POR_PAGAR>();
            this.CA_HORARIOS = new HashSet<CA_HORARIOS>();
            this.RO_ROLES = new HashSet<RO_ROLES>();
            this.CP_CUENTAS_POR_PAGAR_HISTORICO = new HashSet<CP_CUENTAS_POR_PAGAR_HISTORICO>();
            this.CA_DEPARTAMENTOS = new HashSet<CA_DEPARTAMENTOS>();
        }
    
        public int CEC_KEYCEC { get; set; }
        public Nullable<int> TIE_KEYTIE { get; set; }
        public string CEC_DESCRI { get; set; }
        public System.DateTime CEN_FEULAC { get; set; }
        public System.DateTime CEC_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR> CP_CUENTAS_POR_PAGAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_HORARIOS> CA_HORARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RO_ROLES> RO_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR_HISTORICO> CP_CUENTAS_POR_PAGAR_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_DEPARTAMENTOS> CA_DEPARTAMENTOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
