//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_ESTADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_ESTADOS()
        {
            this.CA_CIUDADES = new HashSet<CA_CIUDADES>();
        }
    
        public int EDO_KEYEDO { get; set; }
        public Nullable<int> PAI_KEYPAI { get; set; }
        public string EDO_NOMBRE { get; set; }
        public string EDO_ABREVI { get; set; }
        public System.DateTime EDO_FEULAC { get; set; }
        public System.DateTime EDO_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CIUDADES> CA_CIUDADES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PAISES CA_PAISES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
