//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_FORMAS_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_FORMAS_PAGO()
        {
            this.CA_MONEDA_DENOMINACION = new HashSet<CA_MONEDA_DENOMINACION>();
            this.CA_PROMOCIONES_FORMAS_PAGO = new HashSet<CA_PROMOCIONES_FORMAS_PAGO>();
            this.CE_CREDITO_EMPLEADOS = new HashSet<CE_CREDITO_EMPLEADOS>();
            this.TC_TIENDAS_CIERRE = new HashSet<TC_TIENDAS_CIERRE>();
            this.TP_TIPO_PAGO_IMPORTE = new HashSet<TP_TIPO_PAGO_IMPORTE>();
            this.TF_TIENDAS_FORMAS_PAGO = new HashSet<TF_TIENDAS_FORMAS_PAGO>();
        }
    
        public int FPA_KEYFPA { get; set; }
        public string FPA_CVEFPA { get; set; }
        public string FPA_DESCRI { get; set; }
        public int FPA_ORDENA { get; set; }
        public int CCO_KEYCCO { get; set; }
        public bool FPA_TARGTA { get; set; }
        public bool FPA_APLMOE { get; set; }
        public System.DateTime FPA_FEULAC { get; set; }
        public System.DateTime FPA_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CUENTAS_CONTABLES CA_CUENTAS_CONTABLES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MONEDA_DENOMINACION> CA_MONEDA_DENOMINACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_FORMAS_PAGO> CA_PROMOCIONES_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CE_CREDITO_EMPLEADOS> CE_CREDITO_EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_TIENDAS_CIERRE> TC_TIENDAS_CIERRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TP_TIPO_PAGO_IMPORTE> TP_TIPO_PAGO_IMPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TF_TIENDAS_FORMAS_PAGO> TF_TIENDAS_FORMAS_PAGO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
