//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_HORARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_HORARIOS()
        {
            this.RO_ROLES = new HashSet<RO_ROLES>();
        }
    
        public int HOR_KEYHOR { get; set; }
        public int CEC_KEYCEC { get; set; }
        public int TIH_KEYTIH { get; set; }
        public System.DateTime HOR_HORIN1 { get; set; }
        public System.DateTime HOR_HORIN2 { get; set; }
        public System.DateTime HOR_HORFI1 { get; set; }
        public System.DateTime HOR_HORFI2 { get; set; }
        public System.DateTime HOR_FEULAC { get; set; }
        public System.DateTime HOR_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CENTROS_COSTOS CA_CENTROS_COSTOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RO_ROLES> RO_ROLES { get; set; }
        public virtual CA_TIPOS_HORARIOS CA_TIPOS_HORARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
