//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_LUGARES_ENTREGAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_LUGARES_ENTREGAS()
        {
            this.OC_ORDENES_COMPRA_DETALLE = new HashSet<OC_ORDENES_COMPRA_DETALLE>();
        }
    
        public int LUE_KEYLUE { get; set; }
        public string LUE_DOMICI { get; set; }
        public string LUE_COLONI { get; set; }
        public string LUE_NUMEXT { get; set; }
        public string LUE_NUMINT { get; set; }
        public string LUE_CODPOS { get; set; }
        public int CIU_KEYCIU { get; set; }
        public System.DateTime LUE_FECALT { get; set; }
        public System.DateTime LUE_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CIUDADES CA_CIUDADES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA_DETALLE> OC_ORDENES_COMPRA_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
