//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_LISTAS_PRECIOS_DETALLE
    {
        public int LPD_KEYIDE { get; set; }
        public int LIP_KEYLIP { get; set; }
        public string PRD_KEYPRD { get; set; }
        public decimal LPD_PRECIO { get; set; }
        public decimal LPD_COSTO { get; set; }
        public System.DateTime LPD_FEULAC { get; set; }
        public System.DateTime LPD_FECALT { get; set; }
        public decimal LPD_PREORI { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_LISTAS_PRECIOS CA_LISTAS_PRECIOS { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
