//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_LISTAS_PRECIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_LISTAS_PRECIOS()
        {
            this.BC_BITACORA_CAMBIOS_PRECIOS = new HashSet<BC_BITACORA_CAMBIOS_PRECIOS>();
            this.CA_LISTAS_PRECIOS_DETALLE = new HashSet<CA_LISTAS_PRECIOS_DETALLE>();
            this.CA_TIENDAS = new HashSet<CA_TIENDAS>();
        }
    
        public int LIP_KEYLIP { get; set; }
        public string LIP_DESCRI { get; set; }
        public decimal LIP_PORINC { get; set; }
        public bool LIP_LISBAS { get; set; }
        public decimal LIP_PORFAC { get; set; }
        public System.DateTime LIP_FEULAC { get; set; }
        public System.DateTime LIP_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_CAMBIOS_PRECIOS> BC_BITACORA_CAMBIOS_PRECIOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LISTAS_PRECIOS_DETALLE> CA_LISTAS_PRECIOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS> CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
