//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_MOTIVOS_CREDITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_MOTIVOS_CREDITO()
        {
            this.CE_CREDITO_EMPLEADOS = new HashSet<CE_CREDITO_EMPLEADOS>();
        }
    
        public int MOC_KEYMOC { get; set; }
        public int PUE_KEYPUE { get; set; }
        public string MOC_CVEMOC { get; set; }
        public string MOC_DESCRI { get; set; }
        public decimal MOC_MONTO { get; set; }
        public System.DateTime MOC_FECALT { get; set; }
        public System.DateTime MOC_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CE_CREDITO_EMPLEADOS> CE_CREDITO_EMPLEADOS { get; set; }
        public virtual CA_PUESTOS CA_PUESTOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
