//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_MONEDA_DENOMINACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_MONEDA_DENOMINACION()
        {
            this.CD_CORTE_CAJA_DETALLE = new HashSet<CD_CORTE_CAJA_DETALLE>();
        }
    
        public int MDE_KEYMDE { get; set; }
        public int MON_KEYMON { get; set; }
        public int FPA_KEYFPA { get; set; }
        public decimal MDE_VALOR { get; set; }
        public System.DateTime MDE_FECALT { get; set; }
        public System.DateTime MDE_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_FORMAS_PAGO CA_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CORTE_CAJA_DETALLE> CD_CORTE_CAJA_DETALLE { get; set; }
        public virtual CA_MONEDAS CA_MONEDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
