//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_MONEDAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_MONEDAS()
        {
            this.CA_CUENTAS_CONTABLES = new HashSet<CA_CUENTAS_CONTABLES>();
            this.CA_MONEDA_DENOMINACION = new HashSet<CA_MONEDA_DENOMINACION>();
            this.CA_TIPOS_CAMBIOS = new HashSet<CA_TIPOS_CAMBIOS>();
            this.DE_DEPOSITOS = new HashSet<DE_DEPOSITOS>();
            this.OC_ORDENES_COMPRA = new HashSet<OC_ORDENES_COMPRA>();
        }
    
        public int MON_KEYMON { get; set; }
        public string MON_DESCRI { get; set; }
        public bool MON_MONNAC { get; set; }
        public System.DateTime MON_FEULAC { get; set; }
        public System.DateTime MON_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CUENTAS_CONTABLES> CA_CUENTAS_CONTABLES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MONEDA_DENOMINACION> CA_MONEDA_DENOMINACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_CAMBIOS> CA_TIPOS_CAMBIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_DEPOSITOS> DE_DEPOSITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA> OC_ORDENES_COMPRA { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
