//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_MEDIOS_PROVEEDOR
    {
        public int MDP_KEYMDP { get; set; }
        public int PRV_KEYPRV { get; set; }
        public int MEC_KEYMEC { get; set; }
        public string MDP_VALCON { get; set; }
        public System.DateTime MDP_FEULAC { get; set; }
        public System.DateTime MDP_FECALT { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_MEDIOS_CONTACTO CA_MEDIOS_CONTACTO { get; set; }
        public virtual CA_PROVEEDORES CA_PROVEEDORES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
