//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PROCESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PROCESOS()
        {
            this.CA_ESTATUS = new HashSet<CA_ESTATUS>();
            this.CD_CODIGOS_AUTORIZACION = new HashSet<CD_CODIGOS_AUTORIZACION>();
            this.EP_ESTATUS_PROCESOS = new HashSet<EP_ESTATUS_PROCESOS>();
            this.SE_SEC_PROCESOS_ESTATUS = new HashSet<SE_SEC_PROCESOS_ESTATUS>();
        }
    
        public int PRO_KEYPRO { get; set; }
        public string PRO_CVEPRO { get; set; }
        public string PRO_DESCRI { get; set; }
        public System.DateTime PRO_FECALT { get; set; }
        public System.DateTime PRO_FEULAC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_ESTATUS> CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGOS_AUTORIZACION> CD_CODIGOS_AUTORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_ESTATUS_PROCESOS> EP_ESTATUS_PROCESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SE_SEC_PROCESOS_ESTATUS> SE_SEC_PROCESOS_ESTATUS { get; set; }
    }
}
