//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PRODUCTOS_DETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PRODUCTOS_DETALLE()
        {
            this.AP_APARTADOS_DETALLE_HISTORICO = new HashSet<AP_APARTADOS_DETALLE_HISTORICO>();
            this.BC_BITACORA_CAMBIOS_PRECIOS = new HashSet<BC_BITACORA_CAMBIOS_PRECIOS>();
            this.BC_BITACORA_COSTO = new HashSet<BC_BITACORA_COSTO>();
            this.CA_LISTAS_PRECIOS_DETALLE = new HashSet<CA_LISTAS_PRECIOS_DETALLE>();
            this.CA_PRODUCTO_RANGO_TALLAS = new HashSet<CA_PRODUCTO_RANGO_TALLAS>();
            this.CA_PROMOCIONES_RANGOS_DETALLE = new HashSet<CA_PROMOCIONES_RANGOS_DETALLE>();
            this.CA_PROMOCIONES_DETALLE = new HashSet<CA_PROMOCIONES_DETALLE>();
            this.CD_CICLICO_DIFERENCIAS = new HashSet<CD_CICLICO_DIFERENCIAS>();
            this.IN_INVENTARIOS_HISTORICO = new HashSet<IN_INVENTARIOS_HISTORICO>();
            this.MP_MOVIMIENTOS_PRODUCTO = new HashSet<MP_MOVIMIENTOS_PRODUCTO>();
        }
    
        public int PRD_KEYIDE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public string PRD_PRDMST { get; set; }
        public int PRV_KEYPRV { get; set; }
        public int PRD_ORDEN { get; set; }
        public Nullable<decimal> PRD_PRICOS { get; set; }
        public decimal PRD_ULTCOS { get; set; }
        public decimal PRD_ACTCOS { get; set; }
        public decimal PRD_COPRAN { get; set; }
        public decimal PRD_COPRAC { get; set; }
        public System.DateTime PRD_FECALT { get; set; }
        public System.DateTime PRD_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE_HISTORICO> AP_APARTADOS_DETALLE_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_CAMBIOS_PRECIOS> BC_BITACORA_CAMBIOS_PRECIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_COSTO> BC_BITACORA_COSTO { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LISTAS_PRECIOS_DETALLE> CA_LISTAS_PRECIOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTO_RANGO_TALLAS> CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_PRODUCTOS CA_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_RANGOS_DETALLE> CA_PROMOCIONES_RANGOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_DETALLE> CA_PROMOCIONES_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CICLICO_DIFERENCIAS> CD_CICLICO_DIFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INVENTARIOS_HISTORICO> IN_INVENTARIOS_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MP_MOVIMIENTOS_PRODUCTO> MP_MOVIMIENTOS_PRODUCTO { get; set; }
        public virtual CA_PROVEEDORES CA_PROVEEDORES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
