//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PLANTILLAS_TALLA
    {
        public int PLT_KEYIDE { get; set; }
        public short PLT_KEYPLT { get; set; }
        public int PLT_KEYDIV { get; set; }
        public string PLT_CVEDIV { get; set; }
        public string PLT_VALTAL { get; set; }
        public bool PLT_ESTATUS { get; set; }
    }
}
