//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PROVEEDORES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PROVEEDORES()
        {
            this.CA_MEDIOS_PROVEEDOR = new HashSet<CA_MEDIOS_PROVEEDOR>();
            this.CA_PRODUCTOS_DETALLE = new HashSet<CA_PRODUCTOS_DETALLE>();
            this.CP_CUENTAS_POR_PAGAR = new HashSet<CP_CUENTAS_POR_PAGAR>();
            this.CP_CUENTAS_POR_PAGAR_HISTORICO = new HashSet<CP_CUENTAS_POR_PAGAR_HISTORICO>();
            this.DP_DEVOLUCIONES_PROVEEDOR = new HashSet<DP_DEVOLUCIONES_PROVEEDOR>();
            this.OC_ORDENES_COMPRA = new HashSet<OC_ORDENES_COMPRA>();
            this.RE_RECIBO_ELECTRONICO = new HashSet<RE_RECIBO_ELECTRONICO>();
        }
    
        public int PRV_KEYPRV { get; set; }
        public Nullable<int> PRV_TIPPER { get; set; }
        public string PRV_NOMPRO { get; set; }
        public string PRV_RFCPRV { get; set; }
        public string PRV_DOMICI { get; set; }
        public string PRV_NUMEXT { get; set; }
        public string PRV_NUMINT { get; set; }
        public string PRV_COLONI { get; set; }
        public string PRV_CODPOS { get; set; }
        public Nullable<int> CIU_KEYCIU { get; set; }
        public int IMP_KEYIMP { get; set; }
        public int PRV_CONDIC { get; set; }
        public decimal PRV_DESCTO { get; set; }
        public int PRV_DIAENT { get; set; }
        public decimal PRV_PORFAC { get; set; }
        public System.DateTime PRV_FEULAC { get; set; }
        public System.DateTime PRV_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CIUDADES CA_CIUDADES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_IMPUESTOS CA_IMPUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_PROVEEDOR> CA_MEDIOS_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_DETALLE> CA_PRODUCTOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR> CP_CUENTAS_POR_PAGAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR_HISTORICO> CP_CUENTAS_POR_PAGAR_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_DEVOLUCIONES_PROVEEDOR> DP_DEVOLUCIONES_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA> OC_ORDENES_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_RECIBO_ELECTRONICO> RE_RECIBO_ELECTRONICO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
