//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PUESTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PUESTOS()
        {
            this.CA_MOTIVOS_CREDITO = new HashSet<CA_MOTIVOS_CREDITO>();
            this.CA_RANGOS_PORCENTAJES_COMISION = new HashSet<CA_RANGOS_PORCENTAJES_COMISION>();
            this.CA_USUARIOS = new HashSet<CA_USUARIOS>();
        }
    
        public int PUE_KEYPUE { get; set; }
        public string PUE_DESCRI { get; set; }
        public System.DateTime PUE_FEULAC { get; set; }
        public System.DateTime PUE_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MOTIVOS_CREDITO> CA_MOTIVOS_CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RANGOS_PORCENTAJES_COMISION> CA_RANGOS_PORCENTAJES_COMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_USUARIOS> CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
    }
}
