//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PRODUCTOS()
        {
            this.CA_PRODUCTO_IMAGENES = new HashSet<CA_PRODUCTO_IMAGENES>();
            this.CA_PRODUCTOS_DETALLE = new HashSet<CA_PRODUCTOS_DETALLE>();
            this.CA_PRODUCTOS_SIMILARES = new HashSet<CA_PRODUCTOS_SIMILARES>();
            this.CA_PRODUCTOS_SIMILARES1 = new HashSet<CA_PRODUCTOS_SIMILARES>();
        }
    
        public int PRD_KEYIDE { get; set; }
        public string PRD_PRDMST { get; set; }
        public string PRD_DESCRI { get; set; }
        public string PRD_DESCOM { get; set; }
        public int TPR_KEYTPR { get; set; }
        public int GEN_KEYGEN { get; set; }
        public int MOD_KEYMOD { get; set; }
        public int COL_KEYCOL { get; set; }
        public int DIV_KEYDIV { get; set; }
        public Nullable<int> USO_KEYUSO { get; set; }
        public int SIL_KEYSIL { get; set; }
        public int MAR_KEYMAR { get; set; }
        public int TEM_KEYTEM { get; set; }
        public Nullable<int> PRE_KEYPRE { get; set; }
        public string PRD_TPOFAB { get; set; }
        public Nullable<int> SAT_KEYSAT { get; set; }
        public decimal PRD_PREMAX { get; set; }
        public System.DateTime PRD_FECMOC { get; set; }
        public System.DateTime PRD_FECALT { get; set; }
        public System.DateTime PRD_FEULAC { get; set; }
        public Nullable<System.DateTime> PRD_FECBAJ { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
        public int RAN_KEYRAN { get; set; }
    
        public virtual CA_COLORES CA_COLORES { get; set; }
        public virtual CA_DIVISIONES CA_DIVISIONES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_GENEROS CA_GENEROS { get; set; }
        public virtual CA_MARCAS CA_MARCAS { get; set; }
        public virtual CA_MODELOS CA_MODELOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTO_IMAGENES> CA_PRODUCTO_IMAGENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_DETALLE> CA_PRODUCTOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_SIMILARES> CA_PRODUCTOS_SIMILARES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_SIMILARES> CA_PRODUCTOS_SIMILARES1 { get; set; }
        public virtual CA_PRODUCTOS_CVESAT CA_PRODUCTOS_CVESAT { get; set; }
        public virtual CA_PRODUCTOS_ESTATUS CA_PRODUCTOS_ESTATUS { get; set; }
        public virtual CA_RANGOS CA_RANGOS { get; set; }
        public virtual CA_SILUETAS CA_SILUETAS { get; set; }
        public virtual CA_TEMPORADAS CA_TEMPORADAS { get; set; }
        public virtual CA_TIPOS_PRODUCTOS CA_TIPOS_PRODUCTOS { get; set; }
        public virtual CA_USOS CA_USOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
