//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PRODUCTO_RANGO_TALLAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_PRODUCTO_RANGO_TALLAS()
        {
            this.AP_APARTADOS_DETALLE = new HashSet<AP_APARTADOS_DETALLE>();
            this.TR_TRANSFERENCIAS_DETALLE = new HashSet<TR_TRANSFERENCIAS_DETALLE>();
            this.IN_INVENTARIOS = new HashSet<IN_INVENTARIOS>();
            this.TD_TRANSACCIONES_DETALLE = new HashSet<TD_TRANSACCIONES_DETALLE>();
            this.PN_PRODUCTOS_NEGADOS = new HashSet<PN_PRODUCTOS_NEGADOS>();
            this.DP_DEVOLUCIONES_PROVEEDOR_DETALLE = new HashSet<DP_DEVOLUCIONES_PROVEEDOR_DETALLE>();
            this.OC_ORDENES_COMPRA_DETALLE = new HashSet<OC_ORDENES_COMPRA_DETALLE>();
            this.MI_MOVIMIENTOS_INVENTARIO = new HashSet<MI_MOVIMIENTOS_INVENTARIO>();
            this.CD_CODIGO_DESCUENTO = new HashSet<CD_CODIGO_DESCUENTO>();
        }
    
        public int PRT_KEYIDE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public System.DateTime PRT_FECALT { get; set; }
        public System.DateTime PRT_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE> AP_APARTADOS_DETALLE { get; set; }
        public virtual CA_CODIGOS_BARRA CA_CODIGOS_BARRA { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_DETALLE> TR_TRANSFERENCIAS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INVENTARIOS> IN_INVENTARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TRANSACCIONES_DETALLE> TD_TRANSACCIONES_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PN_PRODUCTOS_NEGADOS> PN_PRODUCTOS_NEGADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_DEVOLUCIONES_PROVEEDOR_DETALLE> DP_DEVOLUCIONES_PROVEEDOR_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA_DETALLE> OC_ORDENES_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_MOVIMIENTOS_INVENTARIO> MI_MOVIMIENTOS_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGO_DESCUENTO> CD_CODIGO_DESCUENTO { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_RANGOS_DETALLE CA_RANGOS_DETALLE { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
