//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_RANGOS_DETALLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_RANGOS_DETALLE()
        {
            this.CA_PRODUCTO_RANGO_TALLAS = new HashSet<CA_PRODUCTO_RANGO_TALLAS>();
        }
    
        public int RAD_KEYIDE { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int RAD_ORDEN { get; set; }
        public System.DateTime RAD_FEULAC { get; set; }
        public System.DateTime RAD_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTO_RANGO_TALLAS> CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_RANGOS CA_RANGOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
