//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_RANGOS_PORCENTAJES_COMISION
    {
        public int RNG_KEYIDE { get; set; }
        public int PUE_KEYPUE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int RNG_UNIINI { get; set; }
        public int RNG_UNIFIN { get; set; }
        public int RNG_PESINI { get; set; }
        public int RNG_PESFIN { get; set; }
        public int RNG_MARINI { get; set; }
        public int RNG_MARFIN { get; set; }
        public int RNG_EVAINI { get; set; }
        public int RNG_EVAFIN { get; set; }
        public int RNG_ROTINI { get; set; }
        public int RNG_ROTFIN { get; set; }
        public System.DateTime RNG_FECALT { get; set; }
        public System.DateTime RNG_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PUESTOS CA_PUESTOS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
