//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_SUPERVISORES_ZONA
    {
        public int SUZ_KEYIDE { get; set; }
        public int ZON_KEYZON { get; set; }
        public int SUZ_USRSUP { get; set; }
        public System.DateTime SUZ_FECALT { get; set; }
        public System.DateTime SUZ_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        public virtual CA_ZONAS_GEOGRAFICAS CA_ZONAS_GEOGRAFICAS { get; set; }
    }
}
