//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIPO_DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_TIPO_DOCUMENTO()
        {
            this.AP_APARTADOS = new HashSet<AP_APARTADOS>();
            this.CA_FOLIOS = new HashSet<CA_FOLIOS>();
            this.CA_TEXTO_TICKET = new HashSet<CA_TEXTO_TICKET>();
            this.CT_CANCELACION_TICKET = new HashSet<CT_CANCELACION_TICKET>();
            this.FE_FOLIO_FACTURA_ELECTRONICA = new HashSet<FE_FOLIO_FACTURA_ELECTRONICA>();
            this.TC_TIENDAS_CIERRE = new HashSet<TC_TIENDAS_CIERRE>();
            this.TR_TRANSACCIONES = new HashSet<TR_TRANSACCIONES>();
            this.TH_TRAFICO_HISTORICO = new HashSet<TH_TRAFICO_HISTORICO>();
        }
    
        public int TDO_KEYIDE { get; set; }
        public string TDO_KEYTDO { get; set; }
        public string TDO_DESCRI { get; set; }
        public System.DateTime TDO_FEULAC { get; set; }
        public System.DateTime TDO_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS> AP_APARTADOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_FOLIOS> CA_FOLIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TEXTO_TICKET> CA_TEXTO_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CANCELACION_TICKET> CT_CANCELACION_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FE_FOLIO_FACTURA_ELECTRONICA> FE_FOLIO_FACTURA_ELECTRONICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_TIENDAS_CIERRE> TC_TIENDAS_CIERRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSACCIONES> TR_TRANSACCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_TRAFICO_HISTORICO> TH_TRAFICO_HISTORICO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
