//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIPOS_HORARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_TIPOS_HORARIOS()
        {
            this.CA_HORARIOS = new HashSet<CA_HORARIOS>();
        }
    
        public int TIH_KEYTIH { get; set; }
        public string TIH_CVETIH { get; set; }
        public string TIH_DESCRI { get; set; }
        public System.DateTime TIH_FEULAC { get; set; }
        public System.DateTime TIH_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_HORARIOS> CA_HORARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
