//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIENDAS_CONFIGURACION
    {
        public int TIC_KEYTIC { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string TIC_PARTIC { get; set; }
        public string TIC_VALTIC { get; set; }
        public string TIC_DESCRI { get; set; }
        public System.DateTime TIC_FEULAC { get; set; }
        public System.DateTime TIC_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
