//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIPOS_TRANSFERENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_TIPOS_TRANSFERENCIA()
        {
            this.TR_TRANSFERENCIAS = new HashSet<TR_TRANSFERENCIAS>();
            this.TR_TRANSFERENCIAS_CONFIGURACION = new HashSet<TR_TRANSFERENCIAS_CONFIGURACION>();
        }
    
        public int TTR_KEYTTR { get; set; }
        public string TTR_CVETTR { get; set; }
        public string TTR_DESCRI { get; set; }
        public bool TTR_SEMUES { get; set; }
        public System.DateTime TTR_FECALT { get; set; }
        public System.DateTime TTR_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS> TR_TRANSFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_CONFIGURACION> TR_TRANSFERENCIAS_CONFIGURACION { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
