//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIPOS_ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_TIPOS_ORDEN_COMPRA()
        {
            this.OC_ORDENES_COMPRA = new HashSet<OC_ORDENES_COMPRA>();
        }
    
        public int TOC_KEYTOC { get; set; }
        public string TOC_CVETOC { get; set; }
        public string TOC_DESCRI { get; set; }
        public Nullable<System.DateTime> TOC_FEULAC { get; set; }
        public Nullable<System.DateTime> TOC_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA> OC_ORDENES_COMPRA { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
