//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_TIENDAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_TIENDAS()
        {
            this.AP_APARTADOS_HISTORICO = new HashSet<AP_APARTADOS_HISTORICO>();
            this.AS_ASISTENCIAS = new HashSet<AS_ASISTENCIAS>();
            this.BP_BITACORA_POLIZAS = new HashSet<BP_BITACORA_POLIZAS>();
            this.CA_CAJAS_REGISTRADORAS = new HashSet<CA_CAJAS_REGISTRADORAS>();
            this.CA_CENTROS_COSTOS = new HashSet<CA_CENTROS_COSTOS>();
            this.CA_FOLIOS = new HashSet<CA_FOLIOS>();
            this.CA_MEDIOS_TIENDA = new HashSet<CA_MEDIOS_TIENDA>();
            this.CA_OBJETIVOS_MENSUALES = new HashSet<CA_OBJETIVOS_MENSUALES>();
            this.CA_PROMOCIONES_TIENDAS = new HashSet<CA_PROMOCIONES_TIENDAS>();
            this.CA_RANGOS_PORCENTAJES_COMISION = new HashSet<CA_RANGOS_PORCENTAJES_COMISION>();
            this.CA_TEXTO_TICKET = new HashSet<CA_TEXTO_TICKET>();
            this.TF_TIENDAS_FORMAS_PAGO = new HashSet<TF_TIENDAS_FORMAS_PAGO>();
            this.CA_TIENDAS_BANCOS = new HashSet<CA_TIENDAS_BANCOS>();
            this.CA_TIENDAS_CONFIGURACION = new HashSet<CA_TIENDAS_CONFIGURACION>();
            this.CA_USUARIOS = new HashSet<CA_USUARIOS>();
            this.CD_CICLICO_DIFERENCIAS = new HashSet<CD_CICLICO_DIFERENCIAS>();
            this.CD_CODIGO_DESCUENTO = new HashSet<CD_CODIGO_DESCUENTO>();
            this.CR_CICLICO_RECAPITULACION = new HashSet<CR_CICLICO_RECAPITULACION>();
            this.CR_CICLICO_RESUMEN = new HashSet<CR_CICLICO_RESUMEN>();
            this.CT_CANCELACION_TICKET = new HashSet<CT_CANCELACION_TICKET>();
            this.DE_DEPOSITOS = new HashSet<DE_DEPOSITOS>();
            this.TR_TRANSFERENCIAS = new HashSet<TR_TRANSFERENCIAS>();
            this.FE_FOLIO_FACTURA_ELECTRONICA = new HashSet<FE_FOLIO_FACTURA_ELECTRONICA>();
            this.GA_GASTOS_TIENDAS_CONFIG = new HashSet<GA_GASTOS_TIENDAS_CONFIG>();
            this.GA_GASTOS_TIENDAS = new HashSet<GA_GASTOS_TIENDAS>();
            this.IN_INVENTARIOS = new HashSet<IN_INVENTARIOS>();
            this.IN_INVENTARIOS_HISTORICO = new HashSet<IN_INVENTARIOS_HISTORICO>();
            this.MI_MOVIMIENTOS_INVENTARIO = new HashSet<MI_MOVIMIENTOS_INVENTARIO>();
            this.MP_MOVIMIENTOS_PRODUCTO = new HashSet<MP_MOVIMIENTOS_PRODUCTO>();
            this.OC_ORDENES_COMPRA_DETALLE = new HashSet<OC_ORDENES_COMPRA_DETALLE>();
            this.PN_PRODUCTOS_NEGADOS = new HashSet<PN_PRODUCTOS_NEGADOS>();
            this.TR_TRANSFERENCIAS1 = new HashSet<TR_TRANSFERENCIAS>();
            this.SI_SINCRONIZA = new HashSet<SI_SINCRONIZA>();
            this.SP_SCRIPT_PUNTO_VENTA = new HashSet<SP_SCRIPT_PUNTO_VENTA>();
            this.TD_TIENDAS_DOCUMENTOS = new HashSet<TD_TIENDAS_DOCUMENTOS>();
            this.TP_TIPO_PAGO_IMPORTE = new HashSet<TP_TIPO_PAGO_IMPORTE>();
            this.TT_TIENDA_TRANSPORTE = new HashSet<TT_TIENDA_TRANSPORTE>();
        }
    
        public int TIE_KEYTIE { get; set; }
        public int TTI_KEYTTI { get; set; }
        public int CIU_KEYCIU { get; set; }
        public Nullable<int> ZON_KEYZON { get; set; }
        public int IMP_KEYIMP { get; set; }
        public int LIP_KEYLIP { get; set; }
        public string TIE_CVETIE { get; set; }
        public string TIE_NOMBRE { get; set; }
        public string TIE_DOMICI { get; set; }
        public string TIE_NUMEXT { get; set; }
        public string TIE_NUMINT { get; set; }
        public string TIE_COLONI { get; set; }
        public string TIE_CODPOS { get; set; }
        public int TIE_INVENT { get; set; }
        public string TIE_INVMAX { get; set; }
        public int TIE_NUMSKU { get; set; }
        public string TIE_VALUAC { get; set; }
        public string TIE_NUMAFI { get; set; }
        public int TIE_ORDENA { get; set; }
        public Nullable<decimal> TIE_CAPALM { get; set; }
        public int TIE_KEYAUX { get; set; }
        public System.DateTime TIE_FECALT { get; set; }
        public System.DateTime TIE_FEULAC { get; set; }
        public Nullable<System.DateTime> TIE_FECBAJ { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_HISTORICO> AP_APARTADOS_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ASISTENCIAS> AS_ASISTENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BP_BITACORA_POLIZAS> BP_BITACORA_POLIZAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CAJAS_REGISTRADORAS> CA_CAJAS_REGISTRADORAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CENTROS_COSTOS> CA_CENTROS_COSTOS { get; set; }
        public virtual CA_CIUDADES CA_CIUDADES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_FOLIOS> CA_FOLIOS { get; set; }
        public virtual CA_IMPUESTOS CA_IMPUESTOS { get; set; }
        public virtual CA_LISTAS_PRECIOS CA_LISTAS_PRECIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_TIENDA> CA_MEDIOS_TIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_OBJETIVOS_MENSUALES> CA_OBJETIVOS_MENSUALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_TIENDAS> CA_PROMOCIONES_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RANGOS_PORCENTAJES_COMISION> CA_RANGOS_PORCENTAJES_COMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TEXTO_TICKET> CA_TEXTO_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TF_TIENDAS_FORMAS_PAGO> TF_TIENDAS_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS_BANCOS> CA_TIENDAS_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS_CONFIGURACION> CA_TIENDAS_CONFIGURACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_USUARIOS> CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CICLICO_DIFERENCIAS> CD_CICLICO_DIFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGO_DESCUENTO> CD_CODIGO_DESCUENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CICLICO_RECAPITULACION> CR_CICLICO_RECAPITULACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CICLICO_RESUMEN> CR_CICLICO_RESUMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CANCELACION_TICKET> CT_CANCELACION_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_DEPOSITOS> DE_DEPOSITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS> TR_TRANSFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FE_FOLIO_FACTURA_ELECTRONICA> FE_FOLIO_FACTURA_ELECTRONICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS_CONFIG> GA_GASTOS_TIENDAS_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS> GA_GASTOS_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INVENTARIOS> IN_INVENTARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INVENTARIOS_HISTORICO> IN_INVENTARIOS_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_MOVIMIENTOS_INVENTARIO> MI_MOVIMIENTOS_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MP_MOVIMIENTOS_PRODUCTO> MP_MOVIMIENTOS_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA_DETALLE> OC_ORDENES_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PN_PRODUCTOS_NEGADOS> PN_PRODUCTOS_NEGADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS> TR_TRANSFERENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SI_SINCRONIZA> SI_SINCRONIZA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SP_SCRIPT_PUNTO_VENTA> SP_SCRIPT_PUNTO_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TIENDAS_DOCUMENTOS> TD_TIENDAS_DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TP_TIPO_PAGO_IMPORTE> TP_TIPO_PAGO_IMPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TIENDA_TRANSPORTE> TT_TIENDA_TRANSPORTE { get; set; }
        public virtual CA_TIPOS_TIENDA CA_TIPOS_TIENDA { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        public virtual CA_ZONAS_GEOGRAFICAS CA_ZONAS_GEOGRAFICAS { get; set; }
    }
}
