//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CA_USUARIOS()
        {
            this.AD_PAR_APLINET_DETALLE = new HashSet<AD_PAR_APLINET_DETALLE>();
            this.AM_ANIOS_MESES = new HashSet<AM_ANIOS_MESES>();
            this.AP_APARTADOS = new HashSet<AP_APARTADOS>();
            this.AP_APARTADOS_DETALLE = new HashSet<AP_APARTADOS_DETALLE>();
            this.AP_APARTADOS_DETALLE1 = new HashSet<AP_APARTADOS_DETALLE>();
            this.AP_APARTADOS_DETALLE_HISTORICO = new HashSet<AP_APARTADOS_DETALLE_HISTORICO>();
            this.AP_APARTADOS_HISTORICO = new HashSet<AP_APARTADOS_HISTORICO>();
            this.AS_ASISTENCIAS = new HashSet<AS_ASISTENCIAS>();
            this.AS_ASISTENCIAS1 = new HashSet<AS_ASISTENCIAS>();
            this.BC_BIT_CAMBIOS_PRECIOS_TIENDA = new HashSet<BC_BIT_CAMBIOS_PRECIOS_TIENDA>();
            this.BC_BIT_CAMBIOS_PRECIOS_TIENDA1 = new HashSet<BC_BIT_CAMBIOS_PRECIOS_TIENDA>();
            this.BC_BITACORA_CAMBIOS_PRECIOS = new HashSet<BC_BITACORA_CAMBIOS_PRECIOS>();
            this.BC_BITACORA_COSTO = new HashSet<BC_BITACORA_COSTO>();
            this.BI_BITACORA_CAM_VENDEDOR = new HashSet<BI_BITACORA_CAM_VENDEDOR>();
            this.BI_BITACORA_CAM_VENDEDOR1 = new HashSet<BI_BITACORA_CAM_VENDEDOR>();
            this.BI_BITACORA_CAM_VENDEDOR2 = new HashSet<BI_BITACORA_CAM_VENDEDOR>();
            this.BP_BITACORA_POLIZAS = new HashSet<BP_BITACORA_POLIZAS>();
            this.BP_BITACORA_PRECIO = new HashSet<BP_BITACORA_PRECIO>();
            this.CA_ANIOS = new HashSet<CA_ANIOS>();
            this.CA_BANCOS = new HashSet<CA_BANCOS>();
            this.CA_CAJAS_REGISTRADORAS = new HashSet<CA_CAJAS_REGISTRADORAS>();
            this.CA_CATALOGOS = new HashSet<CA_CATALOGOS>();
            this.CA_CATALOGOS_DETALLE = new HashSet<CA_CATALOGOS_DETALLE>();
            this.CA_CAUSAS_DEVOLUCIONES = new HashSet<CA_CAUSAS_DEVOLUCIONES>();
            this.CA_CAUSAS_NEGADOS = new HashSet<CA_CAUSAS_NEGADOS>();
            this.CA_CENTROS_COSTOS = new HashSet<CA_CENTROS_COSTOS>();
            this.CA_CIUDADES = new HashSet<CA_CIUDADES>();
            this.CA_CLIENTES = new HashSet<CA_CLIENTES>();
            this.CA_CODIGOS_BARRA = new HashSet<CA_CODIGOS_BARRA>();
            this.CA_COLORES = new HashSet<CA_COLORES>();
            this.CA_COMPANIA = new HashSet<CA_COMPANIA>();
            this.CA_CUENTAS_CONTABLES = new HashSet<CA_CUENTAS_CONTABLES>();
            this.CA_DEPARTAMENTOS = new HashSet<CA_DEPARTAMENTOS>();
            this.CA_DEVOLUCIONES_CLIENTES = new HashSet<CA_DEVOLUCIONES_CLIENTES>();
            this.CA_DIVISIONES = new HashSet<CA_DIVISIONES>();
            this.CA_ESTADOS = new HashSet<CA_ESTADOS>();
            this.CA_FOLIOS = new HashSet<CA_FOLIOS>();
            this.CA_FORMAS_PAGO = new HashSet<CA_FORMAS_PAGO>();
            this.CA_GASTOS = new HashSet<CA_GASTOS>();
            this.CA_GENEROS = new HashSet<CA_GENEROS>();
            this.CA_HORARIOS = new HashSet<CA_HORARIOS>();
            this.CA_IMPUESTOS = new HashSet<CA_IMPUESTOS>();
            this.CA_INCIDENCIAS = new HashSet<CA_INCIDENCIAS>();
            this.CA_LISTAS_PRECIOS = new HashSet<CA_LISTAS_PRECIOS>();
            this.CA_LISTAS_PRECIOS_DETALLE = new HashSet<CA_LISTAS_PRECIOS_DETALLE>();
            this.CA_LUGARES_ENTREGAS = new HashSet<CA_LUGARES_ENTREGAS>();
            this.CA_MARCAS = new HashSet<CA_MARCAS>();
            this.CA_MEDIOS_CLIENTE = new HashSet<CA_MEDIOS_CLIENTE>();
            this.CA_MEDIOS_CLIENTE_FACTURACION = new HashSet<CA_MEDIOS_CLIENTE_FACTURACION>();
            this.CA_MEDIOS_CONTACTO = new HashSet<CA_MEDIOS_CONTACTO>();
            this.CA_MEDIOS_PROVEEDOR = new HashSet<CA_MEDIOS_PROVEEDOR>();
            this.CA_MEDIOS_TIENDA = new HashSet<CA_MEDIOS_TIENDA>();
            this.CA_MEDIOS_TRANSPORTES = new HashSet<CA_MEDIOS_TRANSPORTES>();
            this.CA_MESES = new HashSet<CA_MESES>();
            this.CA_MODELOS = new HashSet<CA_MODELOS>();
            this.CA_MONEDA_DENOMINACION = new HashSet<CA_MONEDA_DENOMINACION>();
            this.CA_MONEDAS = new HashSet<CA_MONEDAS>();
            this.CA_MOTIVOS_CREDITO = new HashSet<CA_MOTIVOS_CREDITO>();
            this.CA_OBJETIVOS_MENSUALES = new HashSet<CA_OBJETIVOS_MENSUALES>();
            this.CA_PAISES = new HashSet<CA_PAISES>();
            this.CA_PRODUCTO_IMAGENES = new HashSet<CA_PRODUCTO_IMAGENES>();
            this.CA_PRODUCTO_RANGO_TALLAS = new HashSet<CA_PRODUCTO_RANGO_TALLAS>();
            this.CA_PRODUCTOS = new HashSet<CA_PRODUCTOS>();
            this.CA_PRODUCTOS_CVESAT = new HashSet<CA_PRODUCTOS_CVESAT>();
            this.CA_PRODUCTOS_DETALLE = new HashSet<CA_PRODUCTOS_DETALLE>();
            this.CA_PRODUCTOS_ESTATUS = new HashSet<CA_PRODUCTOS_ESTATUS>();
            this.CA_PRODUCTOS_SIMILARES = new HashSet<CA_PRODUCTOS_SIMILARES>();
            this.CA_PROMOCIONES = new HashSet<CA_PROMOCIONES>();
            this.CA_PROMOCIONES_DETALLE = new HashSet<CA_PROMOCIONES_DETALLE>();
            this.CA_PROMOCIONES_FORMAS_PAGO = new HashSet<CA_PROMOCIONES_FORMAS_PAGO>();
            this.CA_PROMOCIONES_RANGOS = new HashSet<CA_PROMOCIONES_RANGOS>();
            this.CA_PROMOCIONES_RANGOS_DETALLE = new HashSet<CA_PROMOCIONES_RANGOS_DETALLE>();
            this.CA_PROMOCIONES_TIENDAS = new HashSet<CA_PROMOCIONES_TIENDAS>();
            this.CA_PROMOCIONES_TIPO = new HashSet<CA_PROMOCIONES_TIPO>();
            this.CA_PROVEEDORES = new HashSet<CA_PROVEEDORES>();
            this.CA_PUESTOS1 = new HashSet<CA_PUESTOS>();
            this.CA_RANGOS = new HashSet<CA_RANGOS>();
            this.CA_RANGOS_DETALLE = new HashSet<CA_RANGOS_DETALLE>();
            this.CA_RANGOS_PORCENTAJES_COMISION = new HashSet<CA_RANGOS_PORCENTAJES_COMISION>();
            this.CA_RESPUESTA_APLINET = new HashSet<CA_RESPUESTA_APLINET>();
            this.CA_SEMANAS = new HashSet<CA_SEMANAS>();
            this.CA_SILUETAS = new HashSet<CA_SILUETAS>();
            this.CA_SUPERVISORES_ZONA = new HashSet<CA_SUPERVISORES_ZONA>();
            this.CA_SUPERVISORES_ZONA1 = new HashSet<CA_SUPERVISORES_ZONA>();
            this.CA_TEMPORADAS = new HashSet<CA_TEMPORADAS>();
            this.CA_TEXTO_TICKET = new HashSet<CA_TEXTO_TICKET>();
            this.CA_TIENDAS1 = new HashSet<CA_TIENDAS>();
            this.CA_TIENDAS_BANCOS = new HashSet<CA_TIENDAS_BANCOS>();
            this.CA_TIENDAS_CONFIGURACION = new HashSet<CA_TIENDAS_CONFIGURACION>();
            this.CA_TIPO_DOCUMENTO = new HashSet<CA_TIPO_DOCUMENTO>();
            this.CA_TIPOS_CAMBIOS = new HashSet<CA_TIPOS_CAMBIOS>();
            this.CA_TIPOS_CLIENTES = new HashSet<CA_TIPOS_CLIENTES>();
            this.CA_TIPOS_DIAS = new HashSet<CA_TIPOS_DIAS>();
            this.CA_TIPOS_ERRORES = new HashSet<CA_TIPOS_ERRORES>();
            this.CA_TIPOS_HORARIOS = new HashSet<CA_TIPOS_HORARIOS>();
            this.CA_TIPOS_MOVIMIENTOS = new HashSet<CA_TIPOS_MOVIMIENTOS>();
            this.CA_TIPOS_ORDEN_COMPRA = new HashSet<CA_TIPOS_ORDEN_COMPRA>();
            this.CA_TIPOS_PRODUCTOS = new HashSet<CA_TIPOS_PRODUCTOS>();
            this.CA_TIPOS_TIENDA = new HashSet<CA_TIPOS_TIENDA>();
            this.CA_TIPOS_TRANSFERENCIA = new HashSet<CA_TIPOS_TRANSFERENCIA>();
            this.CA_TRANSPORTES = new HashSet<CA_TRANSPORTES>();
            this.CA_USOS = new HashSet<CA_USOS>();
            this.TR_TRANSACCIONES = new HashSet<TR_TRANSACCIONES>();
            this.CP_CUENTAS_POR_PAGAR_HISTORICO = new HashSet<CP_CUENTAS_POR_PAGAR_HISTORICO>();
            this.GA_GASTOS_TIENDAS_CONFIG = new HashSet<GA_GASTOS_TIENDAS_CONFIG>();
            this.CE_CREDITO_EMPLEADOS = new HashSet<CE_CREDITO_EMPLEADOS>();
            this.CD_CODIGO_DESCUENTO = new HashSet<CD_CODIGO_DESCUENTO>();
            this.CC_CORTE_CAJA = new HashSet<CC_CORTE_CAJA>();
            this.CA_ZONAS_GEOGRAFICAS = new HashSet<CA_ZONAS_GEOGRAFICAS>();
            this.CC_CORTE_CAJA1 = new HashSet<CC_CORTE_CAJA>();
            this.CD_CICLICO_DIFERENCIAS = new HashSet<CD_CICLICO_DIFERENCIAS>();
            this.CD_CODIGO_DESCUENTO1 = new HashSet<CD_CODIGO_DESCUENTO>();
            this.CD_CODIGOS_AUTORIZACION = new HashSet<CD_CODIGOS_AUTORIZACION>();
            this.CD_CODIGOS_AUTORIZACION1 = new HashSet<CD_CODIGOS_AUTORIZACION>();
            this.CD_CORTE_CAJA_DETALLE = new HashSet<CD_CORTE_CAJA_DETALLE>();
            this.CE_CREDITO_EMPLEADOS1 = new HashSet<CE_CREDITO_EMPLEADOS>();
            this.CF_CLIENTE_FRECUENTE = new HashSet<CF_CLIENTE_FRECUENTE>();
            this.CF_ORDEN_COMPRA = new HashSet<CF_ORDEN_COMPRA>();
            this.CF_PARAMETRO_ORDEN_COMPRA = new HashSet<CF_PARAMETRO_ORDEN_COMPRA>();
            this.CP_CUENTAS_POR_PAGAR = new HashSet<CP_CUENTAS_POR_PAGAR>();
            this.CR_CICLICO_RECAPITULACION = new HashSet<CR_CICLICO_RECAPITULACION>();
            this.CR_CICLICO_RESUMEN = new HashSet<CR_CICLICO_RESUMEN>();
            this.CT_CANCELACION_TICKET = new HashSet<CT_CANCELACION_TICKET>();
            this.CU_CUPONES = new HashSet<CU_CUPONES>();
            this.DE_DEPOSITOS = new HashSet<DE_DEPOSITOS>();
            this.DE_DEPOSITOS1 = new HashSet<DE_DEPOSITOS>();
            this.DP_DEVOLUCIONES_PROVEEDOR = new HashSet<DP_DEVOLUCIONES_PROVEEDOR>();
            this.DP_DEVOLUCIONES_PROVEEDOR_DETALLE = new HashSet<DP_DEVOLUCIONES_PROVEEDOR_DETALLE>();
            this.EE_ERROR_EMBARQUE = new HashSet<EE_ERROR_EMBARQUE>();
            this.EP_ESTATUS_PROCESOS = new HashSet<EP_ESTATUS_PROCESOS>();
            this.FE_FOLIO_FACTURA_ELECTRONICA = new HashSet<FE_FOLIO_FACTURA_ELECTRONICA>();
            this.FL_FLETES = new HashSet<FL_FLETES>();
            this.FS_FOLIOS_SALIDA = new HashSet<FS_FOLIOS_SALIDA>();
            this.GA_GASTOS_TIENDAS = new HashSet<GA_GASTOS_TIENDAS>();
            this.IN_INCIDENCIAS = new HashSet<IN_INCIDENCIAS>();
            this.MA_MOVIMIENTOS_APARTADO = new HashSet<MA_MOVIMIENTOS_APARTADO>();
            this.MI_MOVIMIENTOS_INVENTARIO = new HashSet<MI_MOVIMIENTOS_INVENTARIO>();
            this.MP_MOVIMIENTOS_PRODUCTO = new HashSet<MP_MOVIMIENTOS_PRODUCTO>();
            this.NC_NOTA_CREDITO = new HashSet<NC_NOTA_CREDITO>();
            this.NE_NEGATIVOS = new HashSet<NE_NEGATIVOS>();
            this.OC_ORDENES_COMPRA_DETALLE = new HashSet<OC_ORDENES_COMPRA_DETALLE>();
            this.OC_ORDENES_COMPRA = new HashSet<OC_ORDENES_COMPRA>();
            this.CF_ORDEN_COMPRA_DETALLE = new HashSet<CF_ORDEN_COMPRA_DETALLE>();
            this.PA_PAR_APLINET = new HashSet<PA_PAR_APLINET>();
            this.PN_PRODUCTOS_NEGADOS = new HashSet<PN_PRODUCTOS_NEGADOS>();
            this.RE_RECIBO_ELECTRONICO_DETALLE = new HashSet<RE_RECIBO_ELECTRONICO_DETALLE>();
            this.RE_RECIBO_ELECTRONICO = new HashSet<RE_RECIBO_ELECTRONICO>();
            this.RF_REFERE_FACELEC = new HashSet<RF_REFERE_FACELEC>();
            this.RO_ROLES = new HashSet<RO_ROLES>();
            this.SP_SCRIPT_PUNTO_VENTA = new HashSet<SP_SCRIPT_PUNTO_VENTA>();
            this.TC_TIENDAS_CIERRE = new HashSet<TC_TIENDAS_CIERRE>();
            this.TD_TIENDAS_DOCUMENTOS = new HashSet<TD_TIENDAS_DOCUMENTOS>();
            this.TD_TRANSACCIONES_DETALLE = new HashSet<TD_TRANSACCIONES_DETALLE>();
            this.TD_TRANSACCIONES_DETALLE1 = new HashSet<TD_TRANSACCIONES_DETALLE>();
            this.TR_TRANSFERENCIAS_DETALLE = new HashSet<TR_TRANSFERENCIAS_DETALLE>();
            this.TF_TIENDAS_FORMAS_PAGO = new HashSet<TF_TIENDAS_FORMAS_PAGO>();
            this.TH_TRAFICO_HISTORICO = new HashSet<TH_TRAFICO_HISTORICO>();
            this.TP_TIPO_PAGO_IMPORTE = new HashSet<TP_TIPO_PAGO_IMPORTE>();
            this.TR_TRANSACCIONES1 = new HashSet<TR_TRANSACCIONES>();
            this.TR_TRANSFERENCIAS = new HashSet<TR_TRANSFERENCIAS>();
            this.TR_TRANSFERENCIAS_CONFIGURACION = new HashSet<TR_TRANSFERENCIAS_CONFIGURACION>();
            this.TT_TIENDA_TRANSPORTE = new HashSet<TT_TIENDA_TRANSPORTE>();
            this.TT_TICKET_TARJETA = new HashSet<TT_TICKET_TARJETA>();
            this.TT_TICKET_TARJETA_APARTADO = new HashSet<TT_TICKET_TARJETA_APARTADO>();
            this.VE_VALES_EMPLEADOS = new HashSet<VE_VALES_EMPLEADOS>();
            this.VE_VENTAS_EMPLEADOS = new HashSet<VE_VENTAS_EMPLEADOS>();
            this.IN_INCIDENCIAS1 = new HashSet<IN_INCIDENCIAS>();
            this.VE_VALES_EMPLEADOS1 = new HashSet<VE_VALES_EMPLEADOS>();
        }
    
        public int USR_KEYUSR { get; set; }
        public Nullable<int> TIE_KEYTIE { get; set; }
        public Nullable<int> PUE_KEYPUE { get; set; }
        public string USR_NOMUSR { get; set; }
        public byte[] USR_PSWUSR { get; set; }
        public Nullable<System.Guid> USR_PSWSALT { get; set; }
        public byte[] USR_IMGUSR { get; set; }
        public short USR_APROBA { get; set; }
        public Nullable<System.DateTime> USR_ULACPW { get; set; }
        public short USR_BLOQUE { get; set; }
        public Nullable<System.DateTime> USR_FECBLO { get; set; }
        public Nullable<System.DateTime> USR_FECDSB { get; set; }
        public Nullable<System.DateTime> USR_ULBLOQ { get; set; }
        public short USR_NUMINT { get; set; }
        public int USR_INTENT { get; set; }
        public Nullable<System.DateTime> USR_MOBALI { get; set; }
        public string USR_NOMCOMP { get; set; }
        public string USR_SEMAIL { get; set; }
        public Nullable<System.DateTime> USR_USPSAP { get; set; }
        public Nullable<int> USR_SUPERU { get; set; }
        public string USR_DOMICI { get; set; }
        public string USR_COLONI { get; set; }
        public string USR_CODPOS { get; set; }
        public string USR_NOIMSS { get; set; }
        public byte[] USR_HUELLA { get; set; }
        public System.DateTime USR_FECALT { get; set; }
        public System.DateTime USR_FEULAC { get; set; }
        public Nullable<System.DateTime> USR_FECBAJ { get; set; }
        public string USR_STSUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD_PAR_APLINET_DETALLE> AD_PAR_APLINET_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AM_ANIOS_MESES> AM_ANIOS_MESES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS> AP_APARTADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE> AP_APARTADOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE> AP_APARTADOS_DETALLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_DETALLE_HISTORICO> AP_APARTADOS_DETALLE_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AP_APARTADOS_HISTORICO> AP_APARTADOS_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ASISTENCIAS> AS_ASISTENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AS_ASISTENCIAS> AS_ASISTENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BIT_CAMBIOS_PRECIOS_TIENDA> BC_BIT_CAMBIOS_PRECIOS_TIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BIT_CAMBIOS_PRECIOS_TIENDA> BC_BIT_CAMBIOS_PRECIOS_TIENDA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_CAMBIOS_PRECIOS> BC_BITACORA_CAMBIOS_PRECIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_COSTO> BC_BITACORA_COSTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BI_BITACORA_CAM_VENDEDOR> BI_BITACORA_CAM_VENDEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BI_BITACORA_CAM_VENDEDOR> BI_BITACORA_CAM_VENDEDOR1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BI_BITACORA_CAM_VENDEDOR> BI_BITACORA_CAM_VENDEDOR2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BP_BITACORA_POLIZAS> BP_BITACORA_POLIZAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BP_BITACORA_PRECIO> BP_BITACORA_PRECIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_ANIOS> CA_ANIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_BANCOS> CA_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CAJAS_REGISTRADORAS> CA_CAJAS_REGISTRADORAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CATALOGOS> CA_CATALOGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CATALOGOS_DETALLE> CA_CATALOGOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CAUSAS_DEVOLUCIONES> CA_CAUSAS_DEVOLUCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CAUSAS_NEGADOS> CA_CAUSAS_NEGADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CENTROS_COSTOS> CA_CENTROS_COSTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CIUDADES> CA_CIUDADES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CLIENTES> CA_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CODIGOS_BARRA> CA_CODIGOS_BARRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_COLORES> CA_COLORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_COMPANIA> CA_COMPANIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_CUENTAS_CONTABLES> CA_CUENTAS_CONTABLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_DEPARTAMENTOS> CA_DEPARTAMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_DEVOLUCIONES_CLIENTES> CA_DEVOLUCIONES_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_DIVISIONES> CA_DIVISIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_ESTADOS> CA_ESTADOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_FOLIOS> CA_FOLIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_FORMAS_PAGO> CA_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_GASTOS> CA_GASTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_GENEROS> CA_GENEROS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_HORARIOS> CA_HORARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_IMPUESTOS> CA_IMPUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_INCIDENCIAS> CA_INCIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LISTAS_PRECIOS> CA_LISTAS_PRECIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LISTAS_PRECIOS_DETALLE> CA_LISTAS_PRECIOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_LUGARES_ENTREGAS> CA_LUGARES_ENTREGAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MARCAS> CA_MARCAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_CLIENTE> CA_MEDIOS_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_CLIENTE_FACTURACION> CA_MEDIOS_CLIENTE_FACTURACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_CONTACTO> CA_MEDIOS_CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_PROVEEDOR> CA_MEDIOS_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_TIENDA> CA_MEDIOS_TIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MEDIOS_TRANSPORTES> CA_MEDIOS_TRANSPORTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MESES> CA_MESES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MODELOS> CA_MODELOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MONEDA_DENOMINACION> CA_MONEDA_DENOMINACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MONEDAS> CA_MONEDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_MOTIVOS_CREDITO> CA_MOTIVOS_CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_OBJETIVOS_MENSUALES> CA_OBJETIVOS_MENSUALES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PAISES> CA_PAISES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTO_IMAGENES> CA_PRODUCTO_IMAGENES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTO_RANGO_TALLAS> CA_PRODUCTO_RANGO_TALLAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS> CA_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_CVESAT> CA_PRODUCTOS_CVESAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_DETALLE> CA_PRODUCTOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_ESTATUS> CA_PRODUCTOS_ESTATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PRODUCTOS_SIMILARES> CA_PRODUCTOS_SIMILARES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES> CA_PROMOCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_DETALLE> CA_PROMOCIONES_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_FORMAS_PAGO> CA_PROMOCIONES_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_RANGOS> CA_PROMOCIONES_RANGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_RANGOS_DETALLE> CA_PROMOCIONES_RANGOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_TIENDAS> CA_PROMOCIONES_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROMOCIONES_TIPO> CA_PROMOCIONES_TIPO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PROVEEDORES> CA_PROVEEDORES { get; set; }
        public virtual CA_PUESTOS CA_PUESTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_PUESTOS> CA_PUESTOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RANGOS> CA_RANGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RANGOS_DETALLE> CA_RANGOS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RANGOS_PORCENTAJES_COMISION> CA_RANGOS_PORCENTAJES_COMISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_RESPUESTA_APLINET> CA_RESPUESTA_APLINET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_SEMANAS> CA_SEMANAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_SILUETAS> CA_SILUETAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_SUPERVISORES_ZONA> CA_SUPERVISORES_ZONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_SUPERVISORES_ZONA> CA_SUPERVISORES_ZONA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TEMPORADAS> CA_TEMPORADAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TEXTO_TICKET> CA_TEXTO_TICKET { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS> CA_TIENDAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS_BANCOS> CA_TIENDAS_BANCOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIENDAS_CONFIGURACION> CA_TIENDAS_CONFIGURACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPO_DOCUMENTO> CA_TIPO_DOCUMENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_CAMBIOS> CA_TIPOS_CAMBIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_CLIENTES> CA_TIPOS_CLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_DIAS> CA_TIPOS_DIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_ERRORES> CA_TIPOS_ERRORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_HORARIOS> CA_TIPOS_HORARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_MOVIMIENTOS> CA_TIPOS_MOVIMIENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_ORDEN_COMPRA> CA_TIPOS_ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_PRODUCTOS> CA_TIPOS_PRODUCTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_TIENDA> CA_TIPOS_TIENDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TIPOS_TRANSFERENCIA> CA_TIPOS_TRANSFERENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_TRANSPORTES> CA_TRANSPORTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_USOS> CA_USOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSACCIONES> TR_TRANSACCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR_HISTORICO> CP_CUENTAS_POR_PAGAR_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS_CONFIG> GA_GASTOS_TIENDAS_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CE_CREDITO_EMPLEADOS> CE_CREDITO_EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGO_DESCUENTO> CD_CODIGO_DESCUENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CORTE_CAJA> CC_CORTE_CAJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CA_ZONAS_GEOGRAFICAS> CA_ZONAS_GEOGRAFICAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CORTE_CAJA> CC_CORTE_CAJA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CICLICO_DIFERENCIAS> CD_CICLICO_DIFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGO_DESCUENTO> CD_CODIGO_DESCUENTO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGOS_AUTORIZACION> CD_CODIGOS_AUTORIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CODIGOS_AUTORIZACION> CD_CODIGOS_AUTORIZACION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CORTE_CAJA_DETALLE> CD_CORTE_CAJA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CE_CREDITO_EMPLEADOS> CE_CREDITO_EMPLEADOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_CLIENTE_FRECUENTE> CF_CLIENTE_FRECUENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_ORDEN_COMPRA> CF_ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_PARAMETRO_ORDEN_COMPRA> CF_PARAMETRO_ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CP_CUENTAS_POR_PAGAR> CP_CUENTAS_POR_PAGAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CICLICO_RECAPITULACION> CR_CICLICO_RECAPITULACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CR_CICLICO_RESUMEN> CR_CICLICO_RESUMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_CANCELACION_TICKET> CT_CANCELACION_TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CU_CUPONES> CU_CUPONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_DEPOSITOS> DE_DEPOSITOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DE_DEPOSITOS> DE_DEPOSITOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_DEVOLUCIONES_PROVEEDOR> DP_DEVOLUCIONES_PROVEEDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DP_DEVOLUCIONES_PROVEEDOR_DETALLE> DP_DEVOLUCIONES_PROVEEDOR_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EE_ERROR_EMBARQUE> EE_ERROR_EMBARQUE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EP_ESTATUS_PROCESOS> EP_ESTATUS_PROCESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FE_FOLIO_FACTURA_ELECTRONICA> FE_FOLIO_FACTURA_ELECTRONICA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FL_FLETES> FL_FLETES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FS_FOLIOS_SALIDA> FS_FOLIOS_SALIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GA_GASTOS_TIENDAS> GA_GASTOS_TIENDAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INCIDENCIAS> IN_INCIDENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_MOVIMIENTOS_APARTADO> MA_MOVIMIENTOS_APARTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MI_MOVIMIENTOS_INVENTARIO> MI_MOVIMIENTOS_INVENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MP_MOVIMIENTOS_PRODUCTO> MP_MOVIMIENTOS_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NC_NOTA_CREDITO> NC_NOTA_CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NE_NEGATIVOS> NE_NEGATIVOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA_DETALLE> OC_ORDENES_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA> OC_ORDENES_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_ORDEN_COMPRA_DETALLE> CF_ORDEN_COMPRA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PA_PAR_APLINET> PA_PAR_APLINET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PN_PRODUCTOS_NEGADOS> PN_PRODUCTOS_NEGADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_RECIBO_ELECTRONICO_DETALLE> RE_RECIBO_ELECTRONICO_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_RECIBO_ELECTRONICO> RE_RECIBO_ELECTRONICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RF_REFERE_FACELEC> RF_REFERE_FACELEC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RO_ROLES> RO_ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SP_SCRIPT_PUNTO_VENTA> SP_SCRIPT_PUNTO_VENTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_TIENDAS_CIERRE> TC_TIENDAS_CIERRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TIENDAS_DOCUMENTOS> TD_TIENDAS_DOCUMENTOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TRANSACCIONES_DETALLE> TD_TRANSACCIONES_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TD_TRANSACCIONES_DETALLE> TD_TRANSACCIONES_DETALLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_DETALLE> TR_TRANSFERENCIAS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TF_TIENDAS_FORMAS_PAGO> TF_TIENDAS_FORMAS_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TH_TRAFICO_HISTORICO> TH_TRAFICO_HISTORICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TP_TIPO_PAGO_IMPORTE> TP_TIPO_PAGO_IMPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSACCIONES> TR_TRANSACCIONES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS> TR_TRANSFERENCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_CONFIGURACION> TR_TRANSFERENCIAS_CONFIGURACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TIENDA_TRANSPORTE> TT_TIENDA_TRANSPORTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TICKET_TARJETA> TT_TICKET_TARJETA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TICKET_TARJETA_APARTADO> TT_TICKET_TARJETA_APARTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE_VALES_EMPLEADOS> VE_VALES_EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE_VENTAS_EMPLEADOS> VE_VENTAS_EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_INCIDENCIAS> IN_INCIDENCIAS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE_VALES_EMPLEADOS> VE_VALES_EMPLEADOS1 { get; set; }
    }
}
