//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_CORTE_CAJA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CC_CORTE_CAJA()
        {
            this.CD_CORTE_CAJA_DETALLE = new HashSet<CD_CORTE_CAJA_DETALLE>();
        }
    
        public int CCA_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int CRE_KEYCRE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public System.DateTime CCA_FECCOR { get; set; }
        public Nullable<int> USR_KEYAUT { get; set; }
        public decimal CCA_DIFERE { get; set; }
        public decimal CCA_IMPCAP { get; set; }
        public decimal CCA_IMPSIS { get; set; }
        public System.DateTime CCA_FECALT { get; set; }
        public System.DateTime CCA_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_CAJAS_REGISTRADORAS CA_CAJAS_REGISTRADORAS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CORTE_CAJA_DETALLE> CD_CORTE_CAJA_DETALLE { get; set; }
        public virtual TF_TIENDAS_FORMAS_PAGO TF_TIENDAS_FORMAS_PAGO { get; set; }
    }
}
