//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_CODIGO_DESCUENTO
    {
        public int CDG_KEYCDG { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public Nullable<int> USR_KEYAPL { get; set; }
        public string CDG_ALFNUM { get; set; }
        public decimal CDG_PREANT { get; set; }
        public decimal CDG_PRECIO { get; set; }
        public System.DateTime CDG_FECVIG { get; set; }
        public System.DateTime CDG_FECALT { get; set; }
        public System.DateTime CDG_FEULAC { get; set; }
        public Nullable<System.DateTime> CDG_FECAPL { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTO_RANGO_TALLAS CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
    }
}
