//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_CICLICO_DIFERENCIAS
    {
        public int CDI_KEYIDE { get; set; }
        public string SEM_KEYSEM { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int TIE_KEYTIE { get; set; }
        public decimal CDI_IMPUNI { get; set; }
        public int CDI_PZASOB { get; set; }
        public decimal CDI_IMPSOB { get; set; }
        public string CDI_TALSOB { get; set; }
        public int CDI_PZAFAL { get; set; }
        public string CDI_TALFAL { get; set; }
        public decimal CDI_IMPFAL { get; set; }
        public string CDI_MOTIVO { get; set; }
        public System.DateTime CDI_FEULAC { get; set; }
        public System.DateTime CDI_FECALT { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTOS_DETALLE CA_PRODUCTOS_DETALLE { get; set; }
        public virtual CA_SEMANAS CA_SEMANAS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
