//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_CORTE_CAJA_DETALLE
    {
        public int CMM_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int CRE_KEYCRE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public System.DateTime CCA_FECCOR { get; set; }
        public int MDE_KEYMDE { get; set; }
        public Nullable<int> CCD_CANTID { get; set; }
        public System.DateTime CCD_FECALT { get; set; }
        public System.DateTime CCD_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_MONEDA_DENOMINACION CA_MONEDA_DENOMINACION { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CC_CORTE_CAJA CC_CORTE_CAJA { get; set; }
        public virtual TF_TIENDAS_FORMAS_PAGO TF_TIENDAS_FORMAS_PAGO { get; set; }
    }
}
