//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD_CODIGOS_AUTORIZACION
    {
        public int CDG_KEYCDG { get; set; }
        public int PRO_KEYPRO { get; set; }
        public int EST_ESTATU { get; set; }
        public int CDG_IDEMOV { get; set; }
        public string CDG_MOTIVO { get; set; }
        public string CDG_CODIGO { get; set; }
        public System.DateTime CDG_FECVIG { get; set; }
        public Nullable<System.DateTime> CDG_FECAPL { get; set; }
        public Nullable<int> USR_USRAPL { get; set; }
        public System.DateTime CDG_FECALT { get; set; }
        public System.DateTime CDG_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS1 { get; set; }
        public virtual CA_PROCESOS CA_PROCESOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
    }
}
