//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CE_CREDITO_EMPLEADOS
    {
        public int CCE_KEYIDE { get; set; }
        public int CEE_KEYCEE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int MOC_KEYMOC { get; set; }
        public int USR_KEYEMP { get; set; }
        public int FPA_KEYFPA { get; set; }
        public string CEE_SALDO { get; set; }
        public string CEE_OBSERV { get; set; }
        public System.DateTime CEE_FECVIG { get; set; }
        public System.DateTime CEE_FECALT { get; set; }
        public System.DateTime CEE_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_FORMAS_PAGO CA_FORMAS_PAGO { get; set; }
        public virtual CA_MOTIVOS_CREDITO CA_MOTIVOS_CREDITO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        public virtual TR_TRANSACCIONES TR_TRANSACCIONES { get; set; }
    }
}
