//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CF_ORDEN_COMPRA_DETALLE
    {
        public int OFD_KEYOFD { get; set; }
        public int OCF_KEYOCF { get; set; }
        public decimal OFD_VALOFD { get; set; }
        public string OFD_OBSERV { get; set; }
        public System.DateTime OFD_FECALT { get; set; }
        public System.DateTime OFD_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
        public Nullable<int> POC_KEYPOC { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CF_ORDEN_COMPRA CF_ORDEN_COMPRA { get; set; }
        public virtual CF_PARAMETRO_ORDEN_COMPRA CF_PARAMETRO_ORDEN_COMPRA { get; set; }
    }
}
