//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CF_ORDEN_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CF_ORDEN_COMPRA()
        {
            this.OC_ORDENES_COMPRA = new HashSet<OC_ORDENES_COMPRA>();
            this.CF_ORDEN_COMPRA_DETALLE = new HashSet<CF_ORDEN_COMPRA_DETALLE>();
        }
    
        public int OCF_KEYOCF { get; set; }
        public string OCF_CVEOCF { get; set; }
        public string OCF_DESCRI { get; set; }
        public System.DateTime OCF_FEULAC { get; set; }
        public System.DateTime OCF_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA> OC_ORDENES_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CF_ORDEN_COMPRA_DETALLE> CF_ORDEN_COMPRA_DETALLE { get; set; }
    }
}
