//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ER_ERRORES
    {
        public int ERR_KEYERR { get; set; }
        public string ERR_CVEERR { get; set; }
        public string ERR_DESCRI { get; set; }
        public System.DateTime ERR_FECALT { get; set; }
        public System.DateTime ERR_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    }
}
