//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GA_GASTOS_TIENDAS
    {
        public int GAS_KEYGAS { get; set; }
        public int TIE_KEYTIE { get; set; }
        public System.DateTime GAT_FECGAS { get; set; }
        public int GAT_KEYGAT { get; set; }
        public int CRE_KEYCRE { get; set; }
        public string GAT_NUMDOC { get; set; }
        public decimal GAT_IMPGAS { get; set; }
        public string GAT_OBSERV { get; set; }
        public System.DateTime GAT_FECALT { get; set; }
        public System.DateTime GAT_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
        public byte[] GAS_IMAGEN { get; set; }
    
        public virtual CA_CAJAS_REGISTRADORAS CA_CAJAS_REGISTRADORAS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_GASTOS CA_GASTOS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
