//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_INCIDENCIAS
    {
        public int INC_KEYIDE { get; set; }
        public int INC_KEYINC { get; set; }
        public int USR_KEYEMP { get; set; }
        public System.DateTime INC_FECINC { get; set; }
        public string INC_OBSERV { get; set; }
        public System.DateTime INC_FECALT { get; set; }
        public System.DateTime INC_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_INCIDENCIAS CA_INCIDENCIAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
    }
}
