//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_INVENTARIOS
    {
        public int INV_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int INV_EXILOG { get; set; }
        public int INV_CANAPA { get; set; }
        public System.DateTime INV_FECALT { get; set; }
        public System.DateTime INV_FEULAC { get; set; }
    
        public virtual CA_PRODUCTO_RANGO_TALLAS CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
    }
}
