//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MA_MOVIMIENTOS_APARTADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MA_MOVIMIENTOS_APARTADO()
        {
            this.TT_TICKET_TARJETA_APARTADO = new HashSet<TT_TICKET_TARJETA_APARTADO>();
        }
    
        public int APA_KEYAPA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public int MOA_KEYMOA { get; set; }
        public decimal MOA_ABOMOA { get; set; }
        public System.DateTime MOA_FECALT { get; set; }
        public System.DateTime MOA_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
        public int MMA_KEYMMA { get; set; }
    
        public virtual AP_APARTADOS AP_APARTADOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TT_TICKET_TARJETA_APARTADO> TT_TICKET_TARJETA_APARTADO { get; set; }
        public virtual TF_TIENDAS_FORMAS_PAGO TF_TIENDAS_FORMAS_PAGO { get; set; }
    }
}
