//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_AUTORIZA_DEV_EFECTIVO
    {
        public int ADE_KEYIDE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string ADE_CODAUT { get; set; }
        public Nullable<System.DateTime> ADE_FECVIG { get; set; }
        public string ADE_NUMDOC { get; set; }
        public Nullable<decimal> ADE_IMPORT { get; set; }
        public System.DateTime ADE_FECALT { get; set; }
        public System.DateTime ADE_FEULAC { get; set; }
        public string EST_KEYEST { get; set; }
    
        public virtual TR_TRANSACCIONES TR_TRANSACCIONES { get; set; }
    }
}
