//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NC_NOTA_CREDITO
    {
        public int NOC_KEYIDE { get; set; }
        public int NOC_KEYNOC { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string TDO_KEYTDO { get; set; }
        public int TRA_KEYTRA1 { get; set; }
        public int TIE_KEYTIE1 { get; set; }
        public string TDO_KEYTDO1 { get; set; }
        public string PRD_KEYPRD1 { get; set; }
        public int RAN_KEYRAN1 { get; set; }
        public string RAD_KEYTAL1 { get; set; }
        public int USR_KEYVTA1 { get; set; }
        public int CDV_KEYCDV { get; set; }
        public int TRD_CANTID1 { get; set; }
        public Nullable<int> TRA_KEYTRA2 { get; set; }
        public Nullable<int> TIE_KEYTIE2 { get; set; }
        public string TDO_KEYTDO2 { get; set; }
        public decimal NOC_IMPORT { get; set; }
        public string NOC_OBSERB { get; set; }
        public Nullable<System.DateTime> NOC_FECAPL { get; set; }
        public System.DateTime NOC_FECACT { get; set; }
        public System.DateTime NOC_FECREG { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CAUSAS_DEVOLUCIONES CA_CAUSAS_DEVOLUCIONES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual TR_TRANSACCIONES TR_TRANSACCIONES { get; set; }
    }
}
