//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NE_NEGATIVOS
    {
        public int NEG_KEYIDE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int USR_KEYVTA { get; set; }
        public int USR_KEYUSR { get; set; }
        public int NEG_CANNEG { get; set; }
        public Nullable<int> NEG_CANREC { get; set; }
        public System.DateTime NEG_FEULAC { get; set; }
        public System.DateTime NEG_FECALT { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual TD_TRANSACCIONES_DETALLE TD_TRANSACCIONES_DETALLE { get; set; }
    }
}
