//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OC_ORDENES_COMPRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OC_ORDENES_COMPRA()
        {
            this.BC_BITACORA_COSTO = new HashSet<BC_BITACORA_COSTO>();
            this.TR_TRANSFERENCIAS_DETALLE = new HashSet<TR_TRANSFERENCIAS_DETALLE>();
            this.OC_ORDENES_COMPRA_DETALLE = new HashSet<OC_ORDENES_COMPRA_DETALLE>();
        }
    
        public int OCO_KEYOCO { get; set; }
        public int TOC_KEYTOC { get; set; }
        public int PRV_KEYPRV { get; set; }
        public int MON_KEYMON { get; set; }
        public int OCO_CANORD { get; set; }
        public int OCO_CANREC { get; set; }
        public int OCO_CANCAN { get; set; }
        public decimal OCO_TOTAL { get; set; }
        public System.DateTime OCO_FECORD { get; set; }
        public Nullable<System.DateTime> OCO_FECREC { get; set; }
        public Nullable<System.DateTime> OCO_FECCAN { get; set; }
        public System.DateTime OCO_FECEST { get; set; }
        public Nullable<System.DateTime> OCO_FECAUT { get; set; }
        public string OCO_REFERE { get; set; }
        public string OCO_COMENT { get; set; }
        public string OCO_OBSERV { get; set; }
        public int OCF_KEYOCF { get; set; }
        public System.DateTime OCO_FEULAC { get; set; }
        public System.DateTime OCO_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BC_BITACORA_COSTO> BC_BITACORA_COSTO { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_MONEDAS CA_MONEDAS { get; set; }
        public virtual CA_PROVEEDORES CA_PROVEEDORES { get; set; }
        public virtual CA_TIPOS_ORDEN_COMPRA CA_TIPOS_ORDEN_COMPRA { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CF_ORDEN_COMPRA CF_ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_DETALLE> TR_TRANSFERENCIAS_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OC_ORDENES_COMPRA_DETALLE> OC_ORDENES_COMPRA_DETALLE { get; set; }
    }
}
