//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PA_PAR_APLINET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PA_PAR_APLINET()
        {
            this.AD_PAR_APLINET_DETALLE = new HashSet<AD_PAR_APLINET_DETALLE>();
        }
    
        public int PAP_KEYPAP { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public string PAP_PINPAD { get; set; }
        public string PAP_APLPRO { get; set; }
        public Nullable<short> PAP_NUMMES { get; set; }
        public string PAP_INTERE { get; set; }
        public System.DateTime PAP_FECACT { get; set; }
        public System.DateTime PAP_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AD_PAR_APLINET_DETALLE> AD_PAR_APLINET_DETALLE { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual TF_TIENDAS_FORMAS_PAGO TF_TIENDAS_FORMAS_PAGO { get; set; }
    }
}
