//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RE_RECIBO_ELECTRONICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RE_RECIBO_ELECTRONICO()
        {
            this.RE_RECIBO_ELECTRONICO_DETALLE = new HashSet<RE_RECIBO_ELECTRONICO_DETALLE>();
        }
    
        public int REE_KEYIDE { get; set; }
        public string REE_NUMFAC { get; set; }
        public int PRV_KEYPRV { get; set; }
        public System.DateTime REE_FECFAC { get; set; }
        public Nullable<decimal> REE_COSORD { get; set; }
        public int REE_TIPPRO { get; set; }
        public System.DateTime REE_FECSYS { get; set; }
        public System.DateTime REE_FECREC { get; set; }
        public System.DateTime REE_FECCXP { get; set; }
        public System.DateTime REE_FECPAG { get; set; }
        public int REE_CONSEC { get; set; }
        public string REE_KEYDOC { get; set; }
        public string REE_USRWEB { get; set; }
        public string REE_USREG { get; set; }
        public Nullable<int> REE_PDFDOC { get; set; }
        public Nullable<int> REE_NOMDOC { get; set; }
        public Nullable<int> REE_XMLDOC { get; set; }
        public Nullable<decimal> REE_SUBTOT { get; set; }
        public Nullable<decimal> REE_IVATOT { get; set; }
        public Nullable<decimal> REE_IMPTOT { get; set; }
        public Nullable<int> REE_PZATOT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PROVEEDORES CA_PROVEEDORES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RE_RECIBO_ELECTRONICO_DETALLE> RE_RECIBO_ELECTRONICO_DETALLE { get; set; }
    }
}
