//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RE_RECIBO_ELECTRONICO_DETALLE
    {
        public int RED_KEYIDE { get; set; }
        public string REE_NUMFAC { get; set; }
        public int PRV_KEYPRV { get; set; }
        public int OCO_KEYOCO { get; set; }
        public int TIE_KEYTIE { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public int LUE_KEYLUE { get; set; }
        public decimal RED_COSPRD { get; set; }
        public Nullable<int> RED_CANTID { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual OC_ORDENES_COMPRA_DETALLE OC_ORDENES_COMPRA_DETALLE { get; set; }
        public virtual RE_RECIBO_ELECTRONICO RE_RECIBO_ELECTRONICO { get; set; }
    }
}
