//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RO_ROLES
    {
        public int ROL_KEYIDE { get; set; }
        public System.DateTime ROL_FECROL { get; set; }
        public string SEM_KEYSEM { get; set; }
        public int CEC_KEYCEC { get; set; }
        public int TID_KEYTID { get; set; }
        public int HOR_KEYHOR { get; set; }
        public System.DateTime ROL_FEULAC { get; set; }
        public System.DateTime ROL_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CENTROS_COSTOS CA_CENTROS_COSTOS { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_HORARIOS CA_HORARIOS { get; set; }
        public virtual CA_SEMANAS CA_SEMANAS { get; set; }
        public virtual CA_TIPOS_DIAS CA_TIPOS_DIAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
