//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_COMPANIAS
    {
        public int COM_KEYCOM { get; set; }
        public string COM_DESCRI { get; set; }
        public System.DateTime COM_FECALT { get; set; }
        public System.DateTime COM_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
    }
}
