//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SE_SEC_PROCESOS_ESTATUS
    {
        public string EST_KEYSTI { get; set; }
        public string EST_KEYSTF { get; set; }
        public int PRO_KEYPRO { get; set; }
    
        public virtual CA_PROCESOS CA_PROCESOS { get; set; }
    }
}
