//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_SCRIPT_PUNTO_VENTA
    {
        public int SPV_KEYIDE { get; set; }
        public int SPV_KEYSPV { get; set; }
        public string SPV_SCRIPT { get; set; }
        public System.DateTime SPV_FECACT { get; set; }
        public int TIE_KEYTIE { get; set; }
        public System.DateTime SPV_FECAPL { get; set; }
        public System.DateTime SPV_FECPRO { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
        public System.DateTime SPV_FECALT { get; set; }
        public System.DateTime SPV_FEULAC { get; set; }
        public string SPV_ERRSCR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
