//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TC_TIENDAS_CIERRE
    {
        public int TIC_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public System.DateTime TIE_FECCIE { get; set; }
        public decimal TIC_MONCIE { get; set; }
        public System.DateTime TIC_FEULAC { get; set; }
        public System.DateTime TIC_FECALT { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_FORMAS_PAGO CA_FORMAS_PAGO { get; set; }
        public virtual CA_TIPO_DOCUMENTO CA_TIPO_DOCUMENTO { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual TF_TIENDAS_FORMAS_PAGO TF_TIENDAS_FORMAS_PAGO { get; set; }
    }
}
