//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_TIENDAS_FORMAS_PAGO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TF_TIENDAS_FORMAS_PAGO()
        {
            this.CC_CORTE_CAJA = new HashSet<CC_CORTE_CAJA>();
            this.CD_CORTE_CAJA_DETALLE = new HashSet<CD_CORTE_CAJA_DETALLE>();
            this.MA_MOVIMIENTOS_APARTADO = new HashSet<MA_MOVIMIENTOS_APARTADO>();
            this.PA_PAR_APLINET = new HashSet<PA_PAR_APLINET>();
            this.TC_TIENDAS_CIERRE = new HashSet<TC_TIENDAS_CIERRE>();
        }
    
        public int TFP_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int FPA_KEYFPA { get; set; }
        public bool TFP_SEMUES { get; set; }
        public System.DateTime TFP_FEULAC { get; set; }
        public System.DateTime TFP_FECALT { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_FORMAS_PAGO CA_FORMAS_PAGO { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CC_CORTE_CAJA> CC_CORTE_CAJA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CD_CORTE_CAJA_DETALLE> CD_CORTE_CAJA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MA_MOVIMIENTOS_APARTADO> MA_MOVIMIENTOS_APARTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PA_PAR_APLINET> PA_PAR_APLINET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TC_TIENDAS_CIERRE> TC_TIENDAS_CIERRE { get; set; }
    }
}
