//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TRANSFERENCIAS_DETALLE
    {
        public int TDE_KEYIDE { get; set; }
        public int TRF_KEYTRF { get; set; }
        public string PRD_KEYPRD { get; set; }
        public int RAN_KEYRAN { get; set; }
        public string RAD_KEYTAL { get; set; }
        public Nullable<int> TDE_CANSOL { get; set; }
        public Nullable<int> TDE_CANCAP { get; set; }
        public Nullable<int> TDE_CANENV { get; set; }
        public Nullable<int> TDE_CANREC { get; set; }
        public Nullable<int> TDE_CANCAN { get; set; }
        public Nullable<int> OCO_KEYOCO { get; set; }
        public Nullable<int> CDV_KEYCDV { get; set; }
        public Nullable<System.DateTime> TDE_FECCAN { get; set; }
        public System.DateTime TDE_FECALT { get; set; }
        public System.DateTime TDE_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_CAUSAS_DEVOLUCIONES CA_CAUSAS_DEVOLUCIONES { get; set; }
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_PRODUCTO_RANGO_TALLAS CA_PRODUCTO_RANGO_TALLAS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual OC_ORDENES_COMPRA OC_ORDENES_COMPRA { get; set; }
        public virtual TR_TRANSFERENCIAS TR_TRANSFERENCIAS { get; set; }
    }
}
