//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TRANSFERENCIAS_CONFIGURACION
    {
        public int TCF_KEYTCF { get; set; }
        public int TTR_KEYTTR { get; set; }
        public int TTI_TTIORI { get; set; }
        public int TTI_TTIDES { get; set; }
        public System.DateTime TCF_FECALT { get; set; }
        public System.DateTime TCF_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIPOS_TIENDA CA_TIPOS_TIENDA { get; set; }
        public virtual CA_TIPOS_TIENDA CA_TIPOS_TIENDA1 { get; set; }
        public virtual CA_TIPOS_TRANSFERENCIA CA_TIPOS_TRANSFERENCIA { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
