//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TRANSFERENCIAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TR_TRANSFERENCIAS()
        {
            this.TR_TRANSFERENCIAS_DETALLE = new HashSet<TR_TRANSFERENCIAS_DETALLE>();
        }
    
        public int TRF_KEYTRF { get; set; }
        public int TTR_KEYTTR { get; set; }
        public Nullable<int> TRN_KEYTRN { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int TIE_KEYTIR { get; set; }
        public string TRF_NOGUIA { get; set; }
        public string TRF_COMENT { get; set; }
        public Nullable<System.DateTime> TRF_FECSOL { get; set; }
        public Nullable<System.DateTime> TRF_FECCAP { get; set; }
        public Nullable<System.DateTime> TRF_FECENV { get; set; }
        public Nullable<System.DateTime> TRF_FECPRR { get; set; }
        public Nullable<System.DateTime> TRF_FECREC { get; set; }
        public Nullable<System.DateTime> TRF_FECCAN { get; set; }
        public System.DateTime TRF_FECALT { get; set; }
        public System.DateTime TRF_FEULAC { get; set; }
        public int USR_KEYUSR { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS1 { get; set; }
        public virtual CA_TIPOS_TRANSFERENCIA CA_TIPOS_TRANSFERENCIA { get; set; }
        public virtual CA_TRANSPORTES CA_TRANSPORTES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TR_TRANSFERENCIAS_DETALLE> TR_TRANSFERENCIAS_DETALLE { get; set; }
    }
}
