//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_TIENDA_TRANSPORTE
    {
        public int TIT_KEYIDE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int TRN_KEYTRN { get; set; }
        public int USR_KEYUSR { get; set; }
        public Nullable<int> TIT_COSFLE { get; set; }
        public System.DateTime TIT_FEULAC { get; set; }
        public System.DateTime TIT_FECALT { get; set; }
        public int EST_KEYEST { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_TIENDAS CA_TIENDAS { get; set; }
        public virtual CA_TRANSPORTES CA_TRANSPORTES { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
    }
}
