//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_VALES_EMPLEADOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE_VALES_EMPLEADOS()
        {
            this.VE_VENTAS_EMPLEADOS = new HashSet<VE_VENTAS_EMPLEADOS>();
        }
    
        public int VAE_KEYVAE { get; set; }
        public int EMP_KEYEMP { get; set; }
        public decimal VAE_CREDITO { get; set; }
        public string VAE_CODIGO { get; set; }
        public int VAE_ARTICU { get; set; }
        public int VAE_CREART { get; set; }
        public int VAE_DESCRE { get; set; }
        public decimal VAE_DESCUE { get; set; }
        public System.DateTime VAE_FECVIG { get; set; }
        public System.DateTime VAE_FECALT { get; set; }
        public System.DateTime VAE_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VE_VENTAS_EMPLEADOS> VE_VENTAS_EMPLEADOS { get; set; }
    }
}
