//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP.Admin.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE_VENTAS_EMPLEADOS
    {
        public int VEE_KEYVEE { get; set; }
        public int VAE_KEYVAE { get; set; }
        public int TIE_KEYTIE { get; set; }
        public int TRA_KEYTRA { get; set; }
        public string TDO_KEYTDO { get; set; }
        public bool VEE_NOTFIR { get; set; }
        public System.DateTime VEE_FECALT { get; set; }
        public System.DateTime VEE_FEULAC { get; set; }
        public int EST_KEYEST { get; set; }
        public int USR_KEYUSR { get; set; }
    
        public virtual CA_ESTATUS CA_ESTATUS { get; set; }
        public virtual CA_USUARIOS CA_USUARIOS { get; set; }
        public virtual TR_TRANSACCIONES TR_TRANSACCIONES { get; set; }
        public virtual VE_VALES_EMPLEADOS VE_VALES_EMPLEADOS { get; set; }
    }
}
